### ISSUE TITLE
Put chunked collection leaf count on the MetaSequence header, not every node

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#1279]
Follow up to #764.

#764 was closed with efficient set/map size/len but it could be better:
* Firstly, the number of leaves is redundantly encoded in list/blob nodes. It's redundant because it's already there as part of the indexed sequence.
* Secondly, it's only needed on the header to MetaSequence, not on every node (see https://github.com/attic-labs/noms/issues/764#issuecomment-210643146).

@rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
I thought about this on and off and I'm not convinced it's possible without being forced to read additional child chunks. I'll close and if someone figures it out, we can revisit.
