### ISSUE TITLE
Implement paths in JS

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#1399]
Summary: this is done in Go, just needs to be done in JS

===

# Problem

We say that Noms is a "content-addressed" database as a shorthand, and that in Noms every value has a hash. In truth, though Noms is centered around content-addressing, and one can compute a hash from every value, it is not true that one can _address_ every value in Noms using its hash alone.

For example:

```
let db = new Database(new MemoryStore());
const a = 42;
const b = {bar:a};
db = db.writeValue({foo:b});
```

At this point, you cannot do `db.readValue(<hash of a>)` or `db.readValue(<hash of b>)`. Those values do not exist as independent chunks in noms, and thus are not _addressable_.

This might not seem like a problem, but it comes up from time to time that we would like a way to talk about values in noms which are not within their own chunks:

* For the output of `noms-diff`, we want to talk about where in the tree a change happened. This requires a way to talk about arbitrary values independent of how they are chunked.

* It would be nice to be able to permalink to any node in splore, but we can't -- we can only link to refs.

* We commonly write software that accepts some noms values as input, but we can only pass values that are at the root of a chunk.

A challenging aspect about coming up with such a mechanism for noms is that our collections can contain a mix of types. So a simple path syntax like `foo/sha1-00000/42/baz` can be ambiguous: an map can have the numeric key `42` and the string key `"42"`. A set can have a string value `"sha-00000"` and a ref value `sha1-00000`.

Another challenge: we need to be able to address complex values that are only used as keys in sets or maps.

# Proposal

A _Noms Path_ (or _path_ for short) is a compact string which is a way to efficiently address any value in Noms.

Here are some example paths in a proposed syntax:

```
// root of dataset "foo"
// field "value"
foo.value

// root of dataset "foo"
// field "value"
// value associated with key 42
foo.value[42]

// root of dataset "foo"
// field "value"
// value associated with key having ref sha1-dc09...
foo.value[#sha1-dc094aa17fdaeb9f95b9b5e2f266a1542fba5469]

// root of dataset "foo"
// field "value"
// key having hash sha1-dc09...
// field "monkey"
// value associated with key "foo"
foo.value[#sha1-dc094aa17fdaeb9f95b9b5e2f266a1542fba5469]@key.monkey["foo"]

// root of chunk with hash sha1-00bd
#sha1-00bd6f8012d09ccbeb08a72e74def78a6d3f3b11

// root of chunk with hash sha1-00bd
// value associated with key 23.1
// value associated with key true
// field "foo"
#sha1-00bd6f8012d09ccbeb08a72e74def78a6d3f3b11[23.1][true].foo
```

Here's the formal syntax:

```
path := (dataset-name | chunk-hash) component*

// dataset-name refers to the commit that is the current root of a named dataset
dataset-name := [a-zA-Z1-9\-_]+

// chunk-hash refers to the value that is the root of the chunk with the given hash
chunk-hash := \#[a-zA-Z1-9\-_]+

component := field | index

// field refers to a value at the field with the specified name in a noms struct
field := \.[a-zA-Z][a-zA-Z1-9_]*

// index refers to a value by indexing into a list, set, or map
// in the case of lists, only number-index is allowed, and must be integral
// in the case of set and map, all index types are allowed
// if the index expression ends with '@key', the value being indexed must be a
// map, and the expression resolves to the 'key' value for the map entry.
index := \[(number-index|bool-index|string-index|hash-index)\](@key)?

// number-index specifies a number to index a list, set, or map by using decimal
// scientific notation
number-index := [0-9\.e]+

// bool-index speifies a boolean to index a set or map by
bool-index := true|false

// string-index specifies a string to index a set or map by. Double-quote must be escaped.
string-index := "[\W ]*"

// hash-index specifies a hash to index a set or map by. this is the hash of the ref of
// a non-bool/string/number value
ref-index := \#[a-zA-Z1-9\-_]+
```

**Comment by rainhead** [comment]
Did this spec get written up somewhere more findable?

**Comment by rainhead** [comment]
Oh, spelling.md points here. Hmm.

**Comment by aboodman** [comment]
We should maybe have a doc index ... Which could include this?

**Comment by kalman** [comment]
boom
