### ISSUE TITLE
Remove ChildValues  & Chunks as public API & Create a consistent, streaming walkValues & walkChunks API

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#1426]
`Value::ChildValues()` doesn't interact well with large collections because it returns a slice of fully decoded values.

Instead, it should probably be an iterator or return a channel or some such.

**Comment by aboodman** [comment]
Assigning to zane but do we have a concrete proposal? @rafael-atticlabs can you make one?

**Comment by rafael-atticlabs** [comment]
`types.WalkValues(vr ValueReader, target Value, valueCb func(v Value))` - calls 'valueCb' once for every reachable *value* from (but excluding) `target`.

`types.WalkRefs(vr ValueReader, target Value, refCb (func(r Ref))` - calls `refCb` once for every *distinct* reachable `Ref`.

**Comment by rafael-atticlabs** [comment]
Updated proposal comment

**Comment by rafael-atticlabs** [comment]
the go part of this is done and js go bye bye.

**Comment by rafael-atticlabs** [comment]
(thanks, @zcstarr )
