### ISSUE TITLE
Auto-generate JS doc

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#1471]
In Go, we get Godoc for free. In JavaScript/Node I'm sure there are tools for this -- probably tons of them, all slightly broken and different.

**Comment by mikegray** [comment]
Once repo became public godoc works - https://godoc.org/github.com/attic-labs/noms. We still have work to do in order to make the content better - and of course we need a JS equivalent.

**Comment by aboodman** [comment]
I don't think we need a bug for "make content better" . That can just be
ongoing task. I'm going to retarget this bug to just JS.

**Comment by arv** [comment]
Some update on the JS front. I've been contributing to [documentation.js](http://documentation.js.org/) and there is one important feature missing. I have a PR for that: https://github.com/documentationjs/documentation/pull/490. With that done we have "a complete" documentation.

We then need to setup a build that generates the HTML and deploy that somewhere.

After that I think we need to tweak the generated HTML quite a bit.

**Comment by arv** [comment]
The documentation.js tool is "good enough" to move on.

For deployment I could set up another ec2 instance or maybe we should just store these in s3 (since these are just static files).

@cmasone-attic @zcstarr @mikegray What do you think?

**Comment by mikegray** [comment]
Probably makes sense to take advantage of AWS CloudFront in front of S3 to serve these if they are all static.

**Comment by cmasone-attic** [comment]
agreed

**Comment by zcstarr** [comment]
agreed as well , I think @mike is right s3 + aws cloudfront sounds smooth

**Comment by arv** [comment]
We now automatically deploy to https://docs.noms.io/js/

I'm closing this. Lets open more specific bugs for things that needs to be improved.

**Comment by rafael-atticlabs** [comment]
So much awesome!
