### ISSUE TITLE
Tighten up 'hints' semantics

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1569]
Right now, there's no requirement or guarantee around what the hints point to. They're just bare hashes that get sent over the wire and the remote side is actually quite forgiving. If they reference nothing...then it just ignores them.

We should do better. Either the BatchStore should reject hints that it knows don't point to anything, or -- more likely -- the ValueStore should only provide hints that it _knows_ exist persistently in the BatchStore.

**Comment by rafael-atticlabs** [comment]
buh bye: https://github.com/attic-labs/noms/commit/de76d37f098d4873665fe27a73d5fa5fb7162d66
