### ISSUE TITLE
Make Refs 'self-validating'

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1573]
We've had a notion that a Database should be able to validate a Ref simply by inspecting it. That is, that a given Database should be able to determine that the Ref points to a Chunk that it has without having to check with its storage backend.

We _think_ that annotating Refs with some information that indicates which Database they came from would allow us to do this. Though that raises the question of what exactly "which Database" means :-) Are any two Database instances backed by the same BatchStore instance equivalent? What if there are two BatchStores that are both talking to the same backend, e.g. Dynamo table or HTTP server?

**Comment by rafael-atticlabs** [comment]
buh bye: https://github.com/attic-labs/noms/commit/de76d37f098d4873665fe27a73d5fa5fb7162d66
