### ISSUE TITLE
ValueStore: We want the 'best' hints

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1575]
Fortunately, I have the best hints. My hints are the best. You won't believe how good the hints are that I have. Nobody you know can get hints as good as these, but I can get them because of how successful I've been. I'm very, very rich.
/Trump

One of the dangers that we face having a long-running hint cache on ValueStore is that over time we can wind up approaching a 1:1 ratio of hints to Chunks required to validate some new Value being written. Consider the case of someone reading out a list, updating an element, committing it back, and then repeating.

```
l := ReadValue(r)  // Now, r is the hint for all chunks directly reachable from l
rH := WriteValue("Hello")
l2 := l.Set(0, rH)
Commit(NewCommit(l2)) // l.Ref() is the hint for validating l2, with new chunks for l2 and "Hello"

rF := WriteValue("Friend")
l3 := l2.Set(1, rF)
Commit(NewCommit(l3)) // l.Ref() AND l2.Ref() as the hints for validating l3, with new chunks for l3 and "Friend"
```

This happens because only l2 can speak to the validity of rF, but l.Ref() is still the stored hint for all the other refs in l3, the ones that were originally seen in l -- even though they're also in l2. We'd like to set the hints for the stuff in l2 to l2, BUT not until it's persisted.

**Comment by rafael-atticlabs** [comment]
buh bye: https://github.com/attic-labs/noms/commit/de76d37f098d4873665fe27a73d5fa5fb7162d66
