### ISSUE TITLE
Can hints also live on Refs?

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1576]
This would finish off #1570, but it's a bit fraught.
1. Tied in with #1569 somewhat; need to be sure that any hint we put inside a Ref only points to a Chunk that's already persisted.
2. We don't want Refs to the same Chunk in the same DB to wind up with different hints
3. We need to be sure that we can still have the 'best' hints for each chunk #1575

**Comment by rafael-atticlabs** [comment]
buh bye: https://github.com/attic-labs/noms/commit/de76d37f098d4873665fe27a73d5fa5fb7162d66
