### ISSUE TITLE
HTTPBatchStore: race between writing chunks and updating root

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1578]
Since we don't do garbage collection yet this isn't currently a problem. But, we currently write chunks to the server and update the root as separate steps with no relationship between them. There's a window, then, when there are a bunch of chunks that aren't yet referenced anywhere, but that we're about to update the root to point to.

**Comment by rafael-atticlabs** [comment]
I feel like this is more of a potential GC issue, but I think we'll need to allow un-reachable values for a variety of reasons. Closing
