### ISSUE TITLE
Does Commit validation fail when re-trying on ErrOptimisticLockFailed?

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1579]
Currently, the writeValue endpoint that RemoteDatabaseClient uses relies on the fact that all novel Chunks come in a single batch, along with a set of hashes that point to already-persisted Chunks that contain refs to any pre-existing chunks referenced by the new stuff. Because the chunks are validated and persisted in one call, but then the root is updated in a separate call (#1578), it's possible for the former to succeed but the latter to fail. In response to this, the client is supposed to grab the new root, which is a Map<string, Ref<Commit>>, update it, write it and try to update the root again:
1. writeValue, culminating in a Map<string, Ref<Commit>> containing a shiny new Commit
2. attempt to updateRoot to point to that new Map -- **FAIL**
3. read the new Root, update it to contain a Ref to the Commit written in step 1
4. writeValue, culminating in a Map<string, Ref<Commit>>...but that Commit is not in this batch, which means its hash _must_ appear in the hints

Currently, ValueStore records the hash of the Commit in step 1 as the hint for itself when it is initially written. That way we have a (trivial) hint for it in step 4, and it doesn't fail. If we stop doing that, we'll need to do something else otherwise this case will fail.

FYI @rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
buh bye: https://github.com/attic-labs/noms/commit/de76d37f098d4873665fe27a73d5fa5fb7162d66
