### ISSUE TITLE
Bring back marshalling mechanism for go

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#1591]
The basic idea is to be able to write go structs and read onto go structs

**Comment by arv** [comment]
We talked about having this read/write to chunks immediately, in other words skip creation of `types.Value`. Is that still the plan? I could see us creating a `types.Value` internally first and then eventually move away from that.

**Comment by aboodman** [comment]
<shrug> - it's clearly going to be slower to make a value first, but maybe
not that much slower. If it's easier to start that way i think it is fine.

**Comment by rafael-atticlabs** [comment]
Agree. We don't have the infrastructure in place yet to marshall directly into sequences, and we should make progress on the marshalling feature.

**Comment by aboodman** [comment]
@vinibaggio - try it out and let us know what you think so far. See https://github.com/attic-labs/noms/blob/master/samples/go/hr/main.go for an example.

**Comment by mikegray** [comment]
That doesn't seem to have been updated yet.

**Comment by aboodman** [comment]
Aw crap. Better link: https://github.com/attic-labs/noms/pull/2375

**Comment by rafael-atticlabs** [comment]
Stoked to see good progress on this.

FWIW, I've been playing with the JS sdk for a while, and I think I've come around to @aboodman's earlier idea that JS should marshall in much the same way go should. That is, if I get a struct out of a list (e.g. `myList.get(0)`), what should be returned to me is a js literal, not a noms struct object.

I was initially against this because I was worried that mixing mutable (js pojos) and immutable (noms list/map/set/etc...) style objects would be confusing. However, I can now see the other side of the coin. For example, if what I want to do is a to logically *alter* a struct (delete a property, set a new property or assign a value to an existing property which has a different type), it's a pain because now I have to get all of values out of the struct, create a new object literal, then create a new struct, then add it back to the list.

I'm now in @aboodman camp on this one, although I'm not quite sure how it works with recursive structs.

**Comment by rafael-atticlabs** [comment]
An even more concrete example of this: If I read a struct out of noms that has a property whose type is a collection. Then I modify the collection to include a new union sub-type and then assign the collection back to the struct, I'll get a type error because the property now contains a collection with a unioned type which wasn't present any more.

Another way to look at this is #2181
