### ISSUE TITLE
Add behavioural tests for JS/Go chunking

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#1600]
We have correctness tests for JS/Go chunking but not much in the way of (explicit) behavioural tests.

Examples:
- Construct a large collection. Check that the average and standard deviation of chunk size is what we expect.
- Modify a large collection. Check that the number of operations (reads, writes) was small as expected, and consistent between JS/Go.

@rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
I feel like maybe the better way to approach this is with perf tests. IOW, we should have perf tests that cover the kinds of things that prolly trees are good at (reading small number of chunks for diff, mutating small amount of data for inserts, etc...). I feel like this kind of more directly measures *why* we might care about this kind of behavior.

@kalman ok to close?

**Comment by kalman** [comment]
For any sort of large scale testing - I agree, perf tests seem fine.

I do think we could do with more unit tests though. https://github.com/attic-labs/noms/blob/master/go/types/set_test.go#L160 is closer to what I had in mind, with expectations for actual average chunk size, standard deviation etc. I'm not aware of having any visibility into this.
