### ISSUE TITLE
diff api should support an iterable interface

### ISSUE THREAD

**Issue by mikegray** [attic-labs/noms#1627]
indexedSequenceDiff, orderedSequenceDiff, listDiff, setDiff, mapDiff, etc. should support an interface that allows for caller to not have to wait for entire diff calculation to finish, for us not to have to calculate entire diff calculation when called, but to continue finding next diffs when next() is called

this will hopefully allow us to remove the loadLimit param on indexedSequenceDiff too.

**Comment by rafael-atticlabs** [comment]
this is done \o/
