### ISSUE TITLE
Test and maybe improve reading during server-side validation

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1647]
If the client has done a bad job of sending hints, ValidatingBatchSink is going to read values serially as it validates.

We should test that case and think about whether we need to make the handler do something fancier -- like maybe process upstreamed chunks in batches and load un-hinted chunks in parallel?

FYI @rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
buh bye: https://github.com/attic-labs/noms/commit/de76d37f098d4873665fe27a73d5fa5fb7162d66
