### ISSUE TITLE
Create continuous perf tests

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#1707]
Figure out how to find out when we regress perf.

**Comment by rafael-atticlabs** [comment]
@kalman, should we close this now in favor of more targeted work?

**Comment by kalman** [comment]
Yes.

(For the record: there is a perf test infrastructure which writes data into noms, and soon to be a graph for viewing the results. It's easy, modulo dealing with Noms APIs, to write another frontend for the perf data which does monitoring).
