### ISSUE TITLE
Consider making Chunks() returns types.RefSlice and ChildValues() return types.ValueSlice

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#1784]
These types are handily sortable and stuff, and are just slices so you can use them that way as well. Is there any reason not to do this? Would it cause a bunch of boxing or something? I don't think it would, since there's no interface stuff, it's just one type vs another.

Thoughts @rafael-atticlabs and @aa?

**Comment by rafael-atticlabs** [comment]
I'd rather do https://github.com/attic-labs/noms/issues/1426. @cmasone-attic, can we close this?

**Comment by cmasone-attic** [comment]
sure
