### ISSUE TITLE
csv-import should read from stdin

### ISSUE THREAD

**Issue by kylelundstedt** [attic-labs/noms#1789]
I'm curious why the `csv-export` command does include the ">" symbol (ala Unix pipe/redirect),

> csv-export ldb:/tmp/noms::films > /tmp/film-locations.csv

while the parallel `csv-import` command does NOT include the "<" symbol (ala Unix pipe/redirect)?

> csv-import ldb:/tmp/noms::films /tmp/film-locations.csv  

Wouldn't something more like the Unix "read a command's input from a disk file "<" make more sense?

> csv-import ldb:/tmp/noms::films < /tmp/film-locations.csv  

Thanks!

**Comment by kalman** [comment]
I've implemented this, more or less: https://github.com/attic-labs/noms/pull/2254
```
> cat *.csv | url-fetch --stdin db::csv/raw
> csv-import -p db::csv/raw.value db::csv
```
