### ISSUE TITLE
Idea: make collection mutation APIs "batched"

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#1819]
# Problem: Prolly tree mutations are hugely expensive

See #1689 for context.

## Proposal: Batch all mutations to prolly trees

```
type Map struct {
...
}

func (m Map) Get(k Value) {
}

func (m Map) Len() uint64 {
}

... etc for all read operations on map ...

func (m Map) Mx() MapMutator {
}

// This struct is mutable, but it returns itself from every call for convenience so that calls can be chained.
type MapMutator struct {
...
}

func (mm MapMutator) Set(k, v Value) MapMutator {
}

func (mm MapMutator) Remove(k Value) MapMutator {
}

func (mm MapMutator) Finish() Map {
}
```

Usage:

```
mx := m.Mx()
for i := 0; i < 100000; i++ {
  mx.Set(types.Number(i), types.Number(i*2))
}
m = mx.Remove("balls").Finish()
```

We'd have similar mutator interfaces for each of our collection types. And we'd remove all the individual mutation methods from Map, Set, and List. The only way to mutate a noms collection would be via these mutator objects.

## Details

Prolly tree mutation is slow partly because every change requires re-chunking, which in turn requires lots of IO to go fetch chunks.

Mutator would batch all of this work together. Mutator would maintain a (potentially huge) sorted set of pending changes, backed by levelDB.

On `Finish()`, Mutator would walk this set of pending changes in parallel with the base prolly tree and construct a new prolly tree in one go.

**Comment by rafael-atticlabs** [comment]
I'm closing this (and transferring priority/ownership) to #2419 since it's a more complete proposal for solving the general problem of streaming changes into a noms graph.

**Comment by aboodman** [comment]
Whoops, I totally forgot about this bug. Sorry.
