### ISSUE TITLE
Path to set/map position

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#1941]
Paths can only address values in set/map keys/values. It would be useful to have a way to address keys/values at positions in the set/map.

This is stable because sets/maps have a well defined ordering.

Strawman: use `{}`, for example given the map:

```
value: {
  "foo": 42,
  "bar": {
    "baz": true
  },
  17: false
}
```

address with

```
> noms show value{0}
42
> noms show value{1}
"bar": {"baz": true}
> noms show value{1}@key
"bar"
> noms show value{1}["baz"]
true
> noms show value{2}
false
> noms show value{2}@key
17
```

Ditto sets. @aboodman

**Comment by kalman** [comment]
New strawman:
* Always make `[42]` index by position.
* For map keys that are numbers, require `[@42]`.

I think this is better than the inconsistency between lists.

**Comment by kalman** [comment]
FINAL STRAWMAN:
* Make `{42}` index by position.
* Support `{42}` syntax on lists for indexing by position.
* Flourish: support `{-1}` for indexing the last position (and `{-2}` for the 2nd last, etc).

**Comment by aboodman** [comment]
lgtm

**Comment by aboodman** [comment]
I think the syntax should be exactly the same for square brackets and curly brackets for lists.

**Comment by kalman** [comment]
Agree
