### ISSUE TITLE
Disallow testify in production binaries

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#1964]
We've had repeated problems with assertions being a drag on performance by allocating in non-failure cases, and by _creating_ failures by attempting to do something to a value in an attempt to provide useful feedback in a failure condition - where the value wasn't ready.

After some discussion in meatspace, the thought is

1) Create a small assertions library for use in production code which makes it alot harder to allocate or do extraneous work in non-failure cases
2) For test code, allow use of testify, but find some way to panic at start-up if testify is included into a production binary
3) For production code, if it's important to output additional information in a failure case, a conditional clause must be explicitly used.

**Comment by aboodman** [comment]
Superceded by #3258.
