### ISSUE TITLE
Take a pass through the major command line tools and play monkey input on them

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#1970]
- csv-importer
- csv-exporter
- noms *

**Comment by aboodman** [comment]
Close?

**Comment by rafael-atticlabs** [comment]
I still think this would be good, at least for one person to do for a half day to generate bugs that'll make the tools feel more solid. If you prefer to close and just let people report bugs as they find them, that's ok too.

**Comment by aboodman** [comment]
Zane, can you take this one? Basically: play qa engineer on all the `noms *` subcommands, as well as `csv-import` and `csv-export`. This will probably generate some easy bugs, which you can then take as well.

**Comment by zcstarr** [comment]
sure  thing i'll take a look!

**Comment by zcstarr** [comment]
I've gone through the tools and picked up some feature requests, filed/assigned myself the related bugs.  I think it would be safe to close this issue.
