### ISSUE TITLE
noms sync reports a quantity of data which is suprising

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#1998]
For csv datasets, the amount of data its reporting is roughly double the actual data logically stored. This is due to all of the repeated type information.

When we are syncing, we decode values. I feel like we should be able to have DecodeValue report total number of "type bytes" within a chunk and we can use math to compute the actual data bytes.

**Comment by rafael-atticlabs** [comment]
Right now the progress report is collecting

- (a) number of chunks known
- (b) number of chunks read
- (c) total number of bytes read

and reporting a % complete based on (b)/(c) and data-rate based on (c) / time.

A better data rate & total data sync'd would match the storage taken on disk, which is compressed (and importantly stripped of all the redundant type information). One approach for this would be to re-compress every chunk in order to get it's compressed size, but that would be a waste of CPU.

Idea: just sample it. I.e. re-compress some small % of chunks fetched in order to get an estimate of their compressed size and multiply that by chunks (b). 

obviously in cases this sampling can go awry, but I'd agree that it's so bad right now, that this would be a huge improvement in all cases I can think of.

**Comment by rafael-atticlabs** [comment]
@aboodman thoughts? `GoodFirstBug` for @ehalpern or @zcstarr ?

**Comment by aboodman** [comment]
@rafael-atticlabs - i think @zcstarr is pretty saturated for next little while on bugs he discovered :). But yeah, potential for @ehalpern.
