### ISSUE TITLE
We need to print progress when committing to a remote store

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2037]
We've gotten to the point where just sending the bytes to the server is the slowest part of most writes. Yay. But now, the progress for e.g., `csv-import`, `sync`, and other things is not as useful because we get near 100% and then it pauses there for awhile during upload.

**Comment by rafael-atticlabs** [comment]
I'm gonna close this one. 1) Because the "commit" phase is quite a bit faster than it was when we wrote this and 2) because I think it's superseded by implementing batched writing which there is now a clear path to.
