### ISSUE TITLE
More datasets to track on demo.noms.io

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2073]
- [x] [Chicago Building Violations](https://data.cityofchicago.org/Buildings/Building-Violations/22u3-xenr)
  - 1.5M rows, 600MB
  - has primary key
  - historical snapshots available
- [x] [New York State Vehicle Registration Database](https://data.ny.gov/Transportation/Vehicle-Snowmobile-and-Boat-Registrations/w4pv-hbkt)
  - 11M rows, 1.2GB
  - There are historical snapshots available
- [x] [New York City Parking Violations](https://data.cityofnewyork.us/City-Government/Parking-Violations-Issued-Fiscal-Year-2016/kiv2-tbus)
  - 1.8GB
  - One dataset per year
  - 2016 dataset appears to be updated daily
  - Appears to be append-only, interesting to see if there are any other changes day-to-day
  - They do a good job of putting zeros in places where they don't have a number, so we can type more things as number
- [ ] [Maryland Real Property Assessments](https://data.maryland.gov/Business-and-Economy/Maryland-Real-Property-Assessments-Hidden-Property/ed4q-f8tm)
  - 4.6GB
  - Updates montly
  - No historical snapshots available
- [ ] [Campaign Finance Filings Submitted to the New York State Board of Elections](https://data.ny.gov/Transparency/Campaign-Finance-Filings-Submitted-to-the-New-York/55r5-jny4)
  - 1.8GB
  - Has historical versions
  - Appears to update about monthly
- [ ] [New York City DOB Environmental Quality Board Violations](https://data.cityofnewyork.us/Housing-Development/DOB-ECB-Violations/6bgk-3dad)
  - 1.1M rows, 500MB
  - Changes daily
  - Historical snapshots unavailable
- [ ] [Colorado weather data from Golden, CO](https://data.colorado.gov/Environment/NREL-Golden-2000-2005-Weather/jd4d-pcwx)
  - 2.7GB
  - No history
  - Updates biyearly?

- [ ] [New York City Authorized Medallion Vehicles](https://data.cityofnewyork.us/Transportation/Medallion-Vehicles-Authorized/rhe8-mgbb)
  - 14M rows, 2.1GB
  - Historical snapshots available
  - Changes _daily_
  - No primary key!?, and data comes out unsorted - either need to find a way to get data sorted, or else figure out a synthetic primary key and implement [nested maps](https://github.com/attic-labs/noms/issues/1956), or else (best) implement [streaming import to set](https://github.com/attic-labs/noms/issues/1929)

**Comment by rafael-atticlabs** [comment]
Can we close this now?

**Comment by aboodman** [comment]
Closing in favor of #2409
