### ISSUE TITLE
demo server running out of space importing large data sets

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2085]
During import of large datasets (and I'm talking running local to the demo server here - like the crons do) the server runs out of space. I believe this is exacerbated by the temporary LDB that clients build up when committing, which doesn't appear to be compressed? Either way it's huge.

The temporary solution here is probably to get a bigger hard drive.

But I'm thinking we _do_ want to run the crons on a different instance so that they can't take down the demo server due to lack of hard drive space.

@aboodman @rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
I think this is no longer applicable.
