### ISSUE TITLE
`noms commit`

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2100]
# Summary

Factor out a `noms commit` command from all existing importers. Take responsibility for commit out of those programs and delegate it to this new command.

# Problem(s)

1. We frequently want the ability to add metadata (#2091) to some importers, but then we end up replicating logic in multiple places.
2. We frequently want the ability to turn duplicate commits into no-ops, but again, this logic would be replicated.
3. We frequently want the ability to aggregate the output of importers into more complex structures. For example, we've had requests to csv-import multiple files as one atomic commit.

# Proposal

```
noms commit [flags] [<path>] <dataset> [--]

Commits `path` to `dataset`. If `--` is present, then the path is read from stdin.

Flags

-allow-dupe             Creates a new commit, even if it would be identical (modulo metadata and parents) to the existing HEAD. Otherwise, such commits are skipped.
-meta key:value         Creates a metadata field called "key" with "value". Value should be human-readable encoded.
-meta-p key:path        Creates a metadata field called "key" set to the value at <path>
-comment value          Alias for -meta 'comment:value'
-date [iso8601-string]  Alias for -meta 'date:str'. 'str' must be iso8601-formatted. If 'str' is empty, it defaults to the current date.
```

Along with implementing this, we'd change things like csv-import to write a root chunk, but not commit it anywhere. We'd also have a convention with all importers to take a `-q[uiet]` flag to suppress ouput except for the final hash, so that you can do things like:

```
csv-import -q ... | noms commit <path> --
```

Note that this proposal alone wouldn't solve problem 3 above, but it would be a step closer. All you'd need is some way to group a bunch of csv imports together into a struct of some sort. Either by adding more flags to `noms commit`, or else implementing something like `noms set make <paths>` (which would construct a set from input paths).

**Comment by mikegray** [comment]
How about instead of `-comment` we use `-message|-m` like `git commit -m "commit message here"`?

**Comment by aboodman** [comment]
Makes sense!

**Comment by mikegray** [comment]
@cmasone-attic based on comments on [datas.Database interface](https://github.com/attic-labs/noms/blob/master/go/datas/database.go#L18) "WriteValue() writes v to this Database, though v is not guaranteed to be be persistent until after a subsequent Commit()".  Based on above comment from @aboodman: "we'd change things like csv-import to write a root chunk, but not commit it anywhere."  Seems like these two notions are working against one another. What do you suggest for enabling WriteValue to be persistent without a Commit? Or am I reading/understanding the ValueReadWriter comment incorrectly?

**Comment by cmasone-attic** [comment]
WriteValue cannot be guaranteed to be persistent without Commit. Commit() is the public API that triggers validation, and it's what pushes chunks to the server if you have a remote database. So...I don't know what to tell you.

**Comment by mikegray** [comment]
What if we added an API to perform something like a `Flush()`, but this wouldn't produce a new Commit/Head? Since these values that would be written are not "referenced" they might be eligible for GC though right? We haven't implemented GC yet, but could see this being a problem. General use case is to be able to write data, probably from multiple separate processes, then Commit once they are all in place to make the update/write "atomic". It very possibly could require new/modified API. Suggestions or further thoughts? @rafael-atticlabs

**Comment by mikegray** [comment]
Going to close this since both 1 and 2 from above are finished. I will open a separate issue for the 3rd problem.
