### ISSUE TITLE
Consider using varint for all quantities in the noms format

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2119]
I had originally reasoned that chunk-level compression (snappy) would do a good enough job removing zeros from quantities (e.g. chunk height, number of elements following in a sequence, etc...), that there was no point to using var int.

Yesterday, I discovered a reason. For #617, I tracked down a bug which caused me to think about the fact that mostly those quantities will be 8 byte values and will tend to be mostly zeros. When we hash over the value bytes, it means that (a) these zeros will tend to skew the target chunk size down and also reduce entropy into the rolling hash.

**Comment by rafael-atticlabs** [comment]
I think this is a natural thing for Noms V8. it's a simple change it'll result in more consistent chunk size.

**Comment by arv** [comment]
I think a better way is to let the encoder use a few more number types. For example, we can use uint8 if the number is a positive int in the range `[0, 255]`, Similarly we can use an int32 if the number is an int in that range.

This would not change that `types.Number` is a `float64` (we want it to be an arbitrary precision number but we haven't done that yet).

**Comment by rafael-atticlabs** [comment]
I'd have to go back and look more closely, but I think we do use uint8 for the few cases that we know the value is bounded, but for most of the *quantities* (`numLeaves`, `height`, etc...), there isn't really a theoretical bound, so its kind of nice to encode with varint.

**Comment by arv** [comment]
I was thinking we would encode as (kind, value) when we know the number can be exactly represented by the kind.

**Comment by rafael-atticlabs** [comment]
I feel pretty strongly this is the right thing to do. I review the encoding again. Currently we only ever use

`uint8` (kind, bool)
`uint32` (internal quantities, like number of fields in a struct or number of items in a sequence)
`uint64` (external quantities, like ref height, numLeaves)

What I'm proposing is that kind & bool will remain one byte, no point in changing that. but all other quantities become `uvarint`

To review, varints are generally a win if you encode small quantities ALOT more than large ones. I think this applies generally to noms encoding. of the above usages, really the only that could plausibly be big is `numLeaves` and even then, the *number* of `numLeaves` encodings which are small will far outstrip the *number* of them which are large.

Take one practical example, a meta sequence requires, at minimum:

-20 byte hash
-8 byte height
-8 byte `numLeaves`

in order to reference a child node. practically speaking, height will *never* be > 2^8 and the *average* `numLeaves` in a store can't every really be larger than 2^16. This means that encoding with varint, the minimum number of bytes to store a reference goes from 36 to ~22. This would allow for ptrees up to 40% wider.

Note that even the idea compressing the bytes passed into the rolling hash will only get us half of the way there because a copy in snappy is always 3 bytes, so at least the two 8 byte values get compressed to 4 bytes each.
