### ISSUE TITLE
OOM during loadtest with 2GB of RAM

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#2126]
@rafael-atticlabs 

I was running @kalman's load test tool on some AWS nodes yesterday, trying to figure out how large the nodes need to be. syncing some datasets definitely ran out of memory on 2GB instances, and I _think_ I saw it run out on instances with 4GB of RAM too. The stack traces were squirreled away in some system logs, so they were kind of unintelligible. It'd behoove someone to run the tool manually and see if they can figure out if this is something we care about. If it's happening on 4GB machines, I think that'd be a problem.

**Comment by rafael-atticlabs** [comment]
I think this is too old and non-specific to be actionable. closing.
