### ISSUE TITLE
408 REQUEST_TIMEOUT when writing large dataset to demo.noms.io

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2146]
The last two cron jobs I've added (ny-vehicle-registrations and nyc-parking-violations-2016) hit this on every run. They are bigger, so I think it's legit. I wonder if there is a dial we can turn on aws somewhere?

**Comment by rafael-atticlabs** [comment]
I'm fairly sure this was the load balancer. I think the import jobs are now targetting localhost. Closing until someone sees this again.

**Comment by kalman** [comment]
Medium term we should be moving the cron jobs off the single demo server instance... or moving away from a single demo server instance. But hopefully once we have multiple servers anyway, this will fix itself.
