### ISSUE TITLE
Do paths automatically traverse refs?

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2172]
And should they?

e.g. `foo.bar[42].monkey`

What if foo is a struct and bar is `Ref<List>`. What if bar is `List<Ref<struct>>` ?

===

Update, after more experience with paths and stuff, I think it sounds great to go with what we were converging on below:

- Yes, we automatically traverse refs
- You can do `@ref` on any path to return its ref
- Since all Noms value (can) have refs, this should always return a value
- But since not all Noms values are stored in the database independently you won't necessarily be able to take the resulting `targetHash` and use it for anything

**Comment by kalman** [comment]
It would be most usable if paths did automatically traverse refs. For completeness I'd like to implement this.

However, as an escape hatch we could provide an `@ref` annotation (similar to `@key`) in order to reference the ref itself, rather than the value it points to?

**Comment by aboodman** [comment]
I guess @ref has to be the last component in the path then?

**Comment by kalman** [comment]
Not necessarily, though at the moment I can't imagine what useful operation you'd want to do to a Ref. Maybe if you wanted to support paths to the type of values: `noms show http://demo.noms.io::some.field@ref@type`.

**Comment by aboodman** [comment]
I'm a little bothered by the increasing tendency to have path components
that "backtrack" this way, but I don't see an obvious problem...?

**Comment by kalman** [comment]
Yeah, I feel that too.

Either way it'd be useful for paths to directly be able to descend into refs, it's awkward at the moment. An annotation like `@deref`/`@read`/`@at` which does the inverse also works, though given you'd far more commonly want to automatically descend into ref, it seems less useful.

Implementation wise I don't want every PathPart having a flag called `IntoRef`, which having the `@ref` might require. If this were purely a descend operation then `@deref` could even be implemented as a PathPart, which is neat. I'll think about it for a bit.

This reminded me to file https://github.com/attic-labs/noms/issues/2269.
