### ISSUE TITLE
type accretion does not work with Go structs

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2181]
```
s := NewStruct("", nil)
// error, because s does not have field bar
s = s.Set("foo", String("bar"))
```

Similarly:

```
s := NewStruct("", map[string]Value{"foo", String("bar")})
// error, because number not same type as string
s = s.Set("foo", Number(42))
```

I sort of expected both these to work and the type to just change, similar to what happens with List.Append() or Set.Insert().

**Comment by rafael-atticlabs** [comment]
Can we close this?

**Comment by aboodman** [comment]
I feel a little weird closing it. It is a weird ergonomic thing that I hit. Perhaps it won't matter in the future, but I'd like to leave it here to, erm, accrete any future reports.
