### ISSUE TITLE
Question (maybe for your FAQ) - how do you compress or deal with never ending growth

### ISSUE THREAD

**Issue by heckj** [attic-labs/noms#2238]
What mechanisms exist within Nom to explicitly compress the persistent storage so that you don't have never-ending growth of the underlying storage mechanisms?

Or put differently, how do you handle scenarios at the logical extension of this space where you run out of persistence store (likely locally) for the information you're tracking in nom?

**Comment by aboodman** [comment]
Hi @heckj, content addressing naturally deduplicates the data that does not change between commits. We also compress data on disk. But in general, the data does just grow. We will eventually have mechanisms to optionally remove old data, or to have "shallow clones", but they are not implemented yet.

**Comment by aboodman** [comment]
Good point though about adding it to the FAQ.

**Comment by heckj** [comment]
Thanks @aboodman !

**Comment by aboodman** [comment]
I took a swing at this: https://github.com/attic-labs/noms/blob/master/doc/faq.md

**Comment by heckj** [comment]
:+1:
