### ISSUE TITLE
noms sync to roll back 1 commit when there are many is slown

### ISSUE THREAD

**Issue by ahl** [attic-labs/noms#2240]
to repro:

`noms sync http://demo.noms.io/ahl::bug2213 /var/tmp/test::biggie`
(wait for a long time)
`noms sync /var/tmp/test::o38hugtf3l1e8rqtj89mijj1dq57eh4m /var/tmp/test::biggie`

This should be fast, but is a lot slower than this:
`noms sync /var/tmp/test::o38hugtf3l1e8rqtj89mijj1dq57eh4m /var/tmp/test::entirelynew`

**Comment by cmasone-attic** [comment]
@rafael-atticlabs 

After looking at this, I realized that we actually currently explicitly disallow this! Noms only allows fast-forwards, and this is actually a rewind. That said, we probably want noms sync to allow this sort of behavior.

You can currently work around this by doing
```
noms ds -d /var/tmp/test::biggie
noms sync /var/tmp/test::o38hugtf3l1e8rqtj89mijj1dq57eh4m /var/tmp/test::biggie
```

Essentially, delete the dataset and then recreate it with the Commit you want at the head. I am going to work on making this case not take so damned long, though, and figure out how noms sync should handle this.
