### ISSUE TITLE
Splore in Safari crashes with "TypeError: Invalid attempt to destructure non-iterable instance"

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2265]
```
TypeError: Invalid attempt to destructure non-iterable instance
uout.js:13:10384
onloadendout.js:13:9380
```
The code is
```
return (0, f.invariant)(u instanceof d.OrderedSequenceCursor), (0, f.invariant)(c instanceof d.OrderedSequenceCursor), y.next = 9, s.default.awrap(a(!1, u, c));
```
which in un-obfuscated land I'm pretty sure is https://github.com/attic-labs/noms/blob/master/js/src/ordered-sequence-diff.js#L81 i.e.
```
[aHasMore, bHasMore] = await doFastForward(false, aParent, bParent);
```
wuh? @arv

**Comment by kalman** [comment]
Maybe a babel bug? The only thing ever returned from `doFastForward` is `[aHasMore, bHasMore]` which is clearly iterable.

**Comment by kalman** [comment]
That said I don't know why splore would be calling that code, since it's only used in diff.

**Comment by kalman** [comment]
@rafael-atticlabs might also be interested.

**Comment by arv** [comment]
Looking
