### ISSUE TITLE
Implement `noms upgrade` for converting noms data from v(N) -> v(N+1)

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2272]
One idea is that this could work in most ways like `noms sync`, but it converts data from the source format to the current format of the noms binary.

**Comment by aboodman** [comment]
@rafael-atticlabs had a really interesting idea about this. We could actually implement it today, 100%, by just implementing an importer from noms v7 TO noms v7. Then when we upgrade to v8, assuming this importer is tested, it will just continue to work. We'll have our importer "in the can" ready to go, for the next format change. Here is how I see it working:

1. Tag Noms today as "v7"
2. In the new v7importer, add things like `import v7types github.com/attic-labs/noms/v7/types`
3. Implement import as a depth first, bottom-up, value-wise copy (using streaming value writers for collections)
4. (Optional, but desirable) use diff to make this incremental

**Comment by aboodman** [comment]
Also, note that this importer would continue to work for v8->v9, v9->v10, actually for any combination of versions, so long as (1) the menagerie of available types in Noms didn't change, and (2) you recompile it with the right import. In fact, you could even imagine having the same program be able to move data between any two versions of the format. Pretty sweet.

**Comment by aboodman** [comment]
This is what I get for claiming it is easy.

**Comment by rafael-atticlabs** [comment]
heh

**Comment by aboodman** [comment]
So easy I can't believe it...
