### ISSUE TITLE
csv-import build issue

### ISSUE THREAD

**Issue by tegansnyder** [attic-labs/noms#2274]
Maybe I've overlooked something. I'm attempting to build the csv-import tool.

```sh
cd noms/samples/go/csv/csv-import
go build
```

Error I receive:
```
./importer.go:52: cannot use "github.com/tsuru/gnuflag".CommandLine (type *"github.com/tsuru/gnuflag".FlagSet) as type *"github.com/attic-labs/noms/vendor/github.com/tsuru/gnuflag".FlagSet in argument to spec.RegisterDatabaseFlags
./importer.go:53: cannot use "github.com/tsuru/gnuflag".CommandLine (type *"github.com/tsuru/gnuflag".FlagSet) as type *"github.com/attic-labs/noms/vendor/github.com/tsuru/gnuflag".FlagSet in argument to profile.RegisterProfileFlags
```

System Info:
```sh
Red Hat Enterprise Linux Server release 7.2 (Maipo)
go version go1.6.3 linux/amd64
```

Any ideas?

**Comment by mikegray** [comment]
Thanks for trying our Noms. Can you double check your $GOPATH and send us the output (pwd) of where you have the noms repo locally too?

**Comment by kalman** [comment]
Another question: do you have github.com/tsuru/gnuflag? I wonder if the way we use go vendoring is messing something up.

**Comment by kalman** [comment]
E.g. `ls $GOPATH/github.com/tsuru/gnuflag`

**Comment by mikegray** [comment]
tsuru is in the noms/vendor/ area AFAICT

**Comment by tegansnyder** [comment]
```sh
[teg csv-import]$ pwd
/usr/local/go/dev/src/github.com/attic-labs/noms/samples/go/csv/csv-import

[teg csv-import]$ echo $GOPATH
/usr/local/go/dev

[teg csv-import]$ ls $GOPATH/github.com/tsuru/gnuflag
ls: cannot access /usr/local/go/dev/github.com/tsuru/gnuflag: No such file or directory
```

**Comment by kalman** [comment]
Hm. The error message makes it look like it's finding 2 copies of gnuflag, one in `github.com/tsuru/gnuflag` and the other (correct) one in `github.com/attic-labs/noms/vendor/github.com/tsuru/gnuflag`.

I realised I should have asked for `ls $GOPATH/src/github.com/tsuru/gnuflag` i.e. was missing the `src` in the component there.

Can you also try building with `export GO15VENDOREXPERIMENT=1`? I don't expect it'll help but maybe Go will surprise me.

**Comment by tegansnyder** [comment]
Looks to be the same.
```sh
[teg csv-import]$ ls $GOPATH/src/github.com/tsuru/gnuflag
ls: cannot access /usr/local/go/dev/src/github.com/tsuru/gnuflag: No such file or directory

[teg csv-import]$ export GO15VENDOREXPERIMENT=1
[teg csv-import]$ go build
# _/usr/local/go/dev/src/github.com/attic-labs/noms/samples/go/csv/csv-import
./importer.go:52: cannot use "github.com/tsuru/gnuflag".CommandLine (type *"github.com/tsuru/gnuflag".FlagSet) as type *"github.com/attic-labs/noms/vendor/github.com/tsuru/gnuflag".FlagSet in argument to spec.RegisterDatabaseFlags
./importer.go:53: cannot use "github.com/tsuru/gnuflag".CommandLine (type *"github.com/tsuru/gnuflag".FlagSet) as type *"github.com/attic-labs/noms/vendor/github.com/tsuru/gnuflag".FlagSet in argument to profile.RegisterProfileFlags
```

**Comment by kalman** [comment]
Bleh.

Perhaps you can investigate yourself whether there is a spurious version of gnuflag sitting around somewhere? It does look like they added a CommandLine thing in a subsequence patch to the initial: https://github.com/tsuru/gnuflag/blame/master/flag.go. The symptoms suggest you have an older version without `CommandLine` and our vendor version with it.

**Comment by tegansnyder** [comment]
Seems unlikely as this is a fresh install, but I will look a bit. Thanks for the assistance so far. I'm pretty interested in evaluating the tools usage. My specific use case is to retrieve the delta's for ETL loads.

**Comment by kalman** [comment]
so... it works on Mac but not on Linux?

**Comment by tegansnyder** [comment]
@kalman correct.

**Comment by kalman** [comment]
Maybe Linux has that Go library installed globally, if that's something Linux supports. We don't have any Linux machines over here unfortunately.

**Comment by aboodman** [comment]
um @kalman we have a crapload of them inside ec2 :).

**Comment by aboodman** [comment]
FTR, I just built/installed csv-import fresh on that same go version, works fine, system info:

```
$  cat /etc/*-release
NAME="Amazon Linux AMI"
VERSION="2016.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2016.03"
PRETTY_NAME="Amazon Linux AMI 2016.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2016.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
Amazon Linux AMI release 2016.03
```

It doesn't look to me like it is finding two copies ... the error says:

cannot use "github.com/tsuru/gnuflag".CommandLine
(type *"github.com/tsuru/gnuflag".FlagSet)

as type *"github.com/attic-labs/noms/vendor/github.com/tsuru/gnuflag".FlagSet
in argument to spec.RegisterDatabaseFlags

So we're trying to pass an instance of `github.com/tsuru/gnuflag.FlagSet` as `github.com/attic-labs/noms/vendor/github.com/tsuru/gnuflag.FlagSet` ... somehow.

I'm not sure where the path with `/vendor/` in it is coming from. That doesn't appear in our source anywhere. Vendoring is not supposed to affect type names.

You've definitely not made any changes to the git repo, right?

Do other go-based projects that use vendoring build on that machine?

I'm sad because your use case sounds ideal and I'd like you to be able to evaluate Noms.

**Comment by aboodman** [comment]
I suppose the next step would be to provision an instance of this version of RHEL inside EC2 just to be sure.

**Comment by tegansnyder** [comment]
I just tried this on a new RHEL machine and it worked. There must be something wrong with the other machine. I was try a fresh install on the other machine. Here are the steps I took on the new machine.

```sh
[teg ~]$ cat /etc/*-release
Red Hat Enterprise Linux Server release 7.2 (Maipo)

[teg ~]$ go version
go version go1.6.3 linux/amd64

[teg ~]$ git clone https://github.com/attic-labs/noms $GOPATH/src/github.com/attic-labs/noms
Cloning into '/usr/local/go/dev/src/github.com/attic-labs/noms'...

[teg ~]$ go install github.com/attic-labs/noms/cmd/noms

[teg csv-import]$ cd $GOPATH/src/github.com/attic-labs/noms
[teg noms]$ cd samples/go/csv/csv-import

[teg csv-import]$ go build
```

I'm closing this because it appears to be a config issue with my other machine. I appreciate everyone's help.

**Comment by aboodman** [comment]
Phew. Glad to hear. I'd love to hear what you get up to with Noms, let us know if slack.noms.io if you have any questions.

**Comment by tegansnyder** [comment]
Thanks @aboodman. I reinstalled it on the other machine and got it to work too! I joined the slack channel. For the moment I'm exploring using it for understanding the deltas that result from a weekly ETL process I have. It would speed up my process if I only process the deltas.
