### ISSUE TITLE
Implement Set Union iterator

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2294]

**Comment by rafael-atticlabs** [comment]
Note that this should be distinguished from producing a new prolly set. The goal here is to simply produce an iterator which returns the union of two sets values.

**Comment by arv** [comment]
Let's call these UnionIterator and not just Union to make this clear.
Having Union that does not return a Set would be confusing.

**Comment by willhite** [comment]
Fixed by PR #2383
