### ISSUE TITLE
Implement streaming prolly tree updates

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2300]
Right now we can process one "splice" mutation to a prolly tree (at given position, remove N values, insert M values), after which we current finalize and produce a full tree.

Implement a mechanism to process N such (ordered) "splice" operations, such that we can streaming a batch of mutations into a prolly tree.

**Comment by aboodman** [comment]
Can someone remind me what the use case is for this? @rafael-atticlabs? @kalman?

**Comment by aboodman** [comment]
@cmasone-attic ?

**Comment by kalman** [comment]
This sounds like another way to frame a more efficient mutation API? I.e. the reason mutations on collections e.g. `map.Set(..).Set(..).Set(..)` is because every call re-chunks. If you could stream them then it wouldn't necessarily re-chunk?

**Comment by aboodman** [comment]
But I mean do we have a concrete need for this in mind?

**Comment by kalman** [comment]
Not that I'm personally aware of.

**Comment by rafael-atticlabs** [comment]
Don't have updates to collections be super slow.

**Comment by cmasone-attic** [comment]
Yeah, isn't this bug basically "Make {Map,Set,List}Mutator a mutator and not a builder"? Merge would use this, for one.

**Comment by aboodman** [comment]
OK, I was looking for a motivating product feature that we're currently working on. Merge is a convincing one.

**Comment by aboodman** [comment]
How does this relate to GraphBuilder? Is the plan to extend GraphBuilder to serve as the API for this?

**Comment by rafael-atticlabs** [comment]
The graph builder solves the problem of operating over more data than will fit into memory. As of now, it only works on first-time construction. If we want to allow it to operate over an existing graph (i.e. updating an index), we'll streaming prolly tree updates, otherwise we'll create an insane amount of garbage.

**Comment by rafael-atticlabs** [comment]
\o/ Yay. This is finally done: https://github.com/attic-labs/noms/commit/1796d2f865f96e8c9a0630e7b07872477046390d
