### ISSUE TITLE
Update Flow

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2301]
We're currently stuck in the past because TOT flow requires all parameterized types to express those parameters and we have alot of js code which doesn't

**Comment by rafael-atticlabs** [comment]
I'm hoping to make some progress towards this moving to a non-parameterized sequence abstraction. @arv, probably hold-off on tackling this until I attempt that.

**Comment by arv** [comment]
I can take care of the Type hierarchy before the Collection hierarchy.
