### ISSUE TITLE
implement streaming utf8 decoder in js

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2304]
i.e. `decodeUtf8(str: string, fn: (b: number) => void)`

if we had this would be unify a bunch of js code and avoid a bunch of allocations.

**Comment by arv** [comment]
I have the code for this in a branch...

**Comment by arv** [comment]
I don't think I understand that type signature?

We currently have:

```js
export function encodeUtf8(str: string, buff: Uint8Array, dv: DataView, offset: number): number {
```

**Comment by rafael-atticlabs** [comment]
the idea is to avoid allocation. it just calls you back once per byte of the encoding.

**Comment by arv** [comment]
I see. However the way things are setup now we just write directly to buf so no allocation is done.
