### ISSUE TITLE
Arbitrary precision number format isn't quite right (I think)

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2307]
I'm worried that there's flexibility in how encode certain numbers. I think we want a fairly simple and correct way to deterministically represent normalized numbers.

For example, I think we current encode `256` as `256` (base) and `(0)` exponent. It would be better to encode as `1` (base) and `7` (exponent)

**Comment by arv** [comment]
That is correct. We should change this next time we do a version change.

**Comment by aboodman** [comment]
This can't be a p1 because it is a format change. Or if it is a p1, then we need a way to queue such changes and not land them immediately, or have them between runtime switches, or something
