### ISSUE TITLE
Accessing root of http server should print an informative message

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2311]
Something like:

```
Hi. This is a Noms http server. To learn more, visit https://github.com/attic-labs/noms.
```

**Comment by jangie** [comment]
I believe the work behind this has been merged. @aboodman can you confirm?

**Comment by mikegray** [comment]
Accessing https://demo.noms.io/ does not print an informative message. That could be because our demo server hasn't been pushed in a bit though.

**Comment by willhite** [comment]
This code has been merged and it does fix the problem but it doesn't fix it on the program that is used for demo.noms.io. This fix works for 'noms serve' but we run the noms/samples/go/demo-server program on demo.noms.io. I was able to reuse some of your code to create a PR #2432 which fixes this for demo-server.
