### ISSUE TITLE
Change dataset spec delimiter

### ISSUE THREAD

**Issue by mikegray** [attic-labs/noms#2323]
It turns out that `::` is meaningful under Windows cmd.exe shell. It is an empty label and sometimes people use it as a comment mechanism (rather than REM).

http://stackoverflow.com/questions/12407800/which-comment-style-should-i-use-in-batch-files

**Comment by aboodman** [comment]
I just found out that ':' is valid in paths according to whatwg url spec ;-). So I'm even less motivated to change this.

(I know, future readers, that this doesn't help with most non-browser url parsers -- but alternatives we are aware of have their own downsides)
