### ISSUE TITLE
We need a slightly smarter approach for type accretion

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2326]
We quickly encounter cases where we have combinatorial explosion of types. For example, if I see data like this:

```
List(
  Struct({a: int, b: int}),
  Struct({a: int, b:string}),
  Struct({b: string, a:int}),
)
```

... we currently infer the types as:

```
List<
  Struct{a:int, b:int} | 
  Struct{a:int, b:string} |
  Struct{a:string, b:int}
>
```

With experience, I think we should instead infer:

```
List<Struct{a:int|string, b:int|string}>
```

... this is less correct, but way easier to think about. And people can still do the more precise thing manually if they really want.

**Comment by arv** [comment]
In type theory, `S<T> | S<V> != S<T | V>` but `S<T | V>` is a subtype of `S<T> | S<V>`.

AI:
- [ ] Make `isSubtype` handle this. https://github.com/attic-labs/noms/blob/master/js/src/assert-type.js#L42
- [ ] Figure out when to use `isSubtype` in `makeCommitType`. https://github.com/attic-labs/noms/blob/master/js/src/commit.js#L78

**Comment by rafael-atticlabs** [comment]
This has been settled via type simplification
