### ISSUE TITLE
Replace github.com/tsuru/gnuflag with github.com/juju/gnuflag

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2331]
github.com/tsuru/gnuflag describes itself as a mirror of launchpad.net/gnuflag, but the official location of launchpad.net/gnuflag is now https://github.com/juju/gnuflag. We should just use https://github.com/juju/gnuflag directly.

**Comment by kalman** [comment]
@arv

**Comment by sunglim** [comment]
I'm happy to address this issue.
