### ISSUE TITLE
JS: Struct field names can collide with ValueBase interface methods

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2332]
If you create a struct (e.g. with jsonToNoms) and you happen to have field names of `type`, `hash` or `chunks`, when code goes to use those apis, it'll receive the value of the field, rather than the `ValueBase` method and then bad things happen.

One way to solve this would be that `Struct` doesn't inherit from `ValueBase` and those methods are moved to some reflectively API, e.g. `typeOfValue` gets the `_type` field of `Struct`.

At very least, struct to throw right now if created with field names which collide with API, rather than failing down the road mysteriously.

**Comment by ahl** [comment]
I hit this today as well.

**Comment by aboodman** [comment]
I don't have a good proposal for a solution. Does anyone? (I feel like every project I work on hits this in some form or other)

**Comment by aboodman** [comment]
I think struct needs to inherit from value -- it's used as a value all over the place.

**Comment by arv** [comment]
One option would be to not reflect these fields as js properties and only expose them through the mirror.

**Comment by rafael-atticlabs** [comment]
+1

**Comment by aboodman** [comment]
:nommy:

**Comment by aboodman** [comment]
:-(
