### ISSUE TITLE
Remove "Q-encoding"

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2411]
`csv-import` imports csv files into containers (lists, maps, sets) of structs. The field names of the struct generally correspond to the column names of the csv. But since Noms struct fields can only have names composed of the chars `[a-zA-Z1-9_-]`, we escape characters outside this.

For example, if you have a csv with the column name `foo bar`, we will create a struct with the field `fooQ20bar`.

We call this escaping scheme "q-encoding", and it turns out to have been a bad idea. Since it is very common to have CSV files with spaces and other special chars, this results in structs that are pretty unreadable.

We should remove this feature from csv importer (and the underlying q-encode code, if that's the only place it is used), and instead:

1. Trim whitespace from ends of input column name
2. Split on whitespace
3. Force the resulting word to camelCase

See #1787, which this bug supersedes for background.

**Comment by aboodman** [comment]
also, as long as you're in here, can you add code to trim space from the column names during import?

**Comment by zcstarr** [comment]
Cool cool make sense to me

**Comment by zcstarr** [comment]
Should this change also be applied to json serialization ?

**Comment by aboodman** [comment]
Oh I forgot the JSON and XML importers used this. Let's leave those using q-encoding for now.

**Comment by mikegray** [comment]
I believe they are all calling [noms/go/types/struct.go:EscapeStructField](https://github.com/attic-labs/noms/blob/master/go/types/struct.go#L179). This same function exists in the JS code, [noms/js/noms/src/struct.js:escapeStructField](https://github.com/attic-labs/noms/blob/master/js/noms/src/struct.js#L307). JS and Go still need to keep matching - so while you are not doing the JSON piece for now, please do think about the JS portion. (Or, I believe @aboodman suggested elsewhere about possibly dropping the JS version of csv-import - that would help too.)

**Comment by zcstarr** [comment]
@mike good point!

**Comment by aboodman** [comment]
Let's drop the js version of csv import.

**Comment by mikegray** [comment]
I just came across another location we are doing something with struct field names. These should probably all be in one place.  I feel like I am piling on here, but please also consider looking at [type.go IsValidStructFieldName](https://github.com/attic-labs/noms/blob/master/go/types/type.go#L174) and the functions below it to see if they can be removed or re-used as you work on the Q-encoding.

**Comment by zcstarr** [comment]
good find I'll try and consolidate the logic, while I'm in there 👍

**Comment by zcstarr** [comment]
I think we can close this issue sound good ?
