### ISSUE TITLE
Remove "Q-encoding"

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2412]
We only use it for csv importer, and it creates super ugly field names. It was a bad idea. It also results in double-escaping in many common workflows.

Instead:

1. Trim whitespace from ends of input column name
2. Split on whitespace
3. Force the resulting word to `camelCase`

See #1787, which this bug supersedes for background.

**Comment by arv** [comment]
Split on whitespace or split on non valid characters?

**Comment by mikegray** [comment]
Duplicate of #2411?

**Comment by aboodman** [comment]
whoops
