### ISSUE TITLE
Continuous Build 

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#2413]
The build at http://jenkins.noms.io/job/NomsServer/ has not run for 2 months. We should build and test everything when committing to master.

We also have a badge saying "Build passing" which is kind of embarrassing.

**Comment by arv** [comment]
@cmasone-attic Do you remember how this used to work?

@kalman @mikegray FIY

**Comment by kalman** [comment]
I think we should clone the NomsPRBuilder job - call it NomsMasterBuilder say - which runs against origin/master instead of every PR. We can set a trigger for that to send breakages to Slack, which we've also lost, and then link the badge to that.

**Comment by cmasone-attic** [comment]
It used to be driven by the Amazon CodePipeline for noms.io and attic.io,
which I believe has been replaced by the pipeline for demo-server.

**Comment by mikegray** [comment]
+1 but also have it build the different architectures/platforms and also publish the binaries.

**Comment by kalman** [comment]
That would be good.

Though baby steps, I'm just going to fix up the builder for now.

**Comment by kalman** [comment]
Well I've set this up... somebody break the build please.

**Comment by kalman** [comment]
Fixed in https://github.com/attic-labs/noms/pull/2418
