### ISSUE TITLE
Color argument is wrong for noms cmd log

### ISSUE THREAD

**Issue by zcstarr** [attic-labs/noms#2442]
noms log --color command  does not do what the help says.  Turning color off should use 0 vs 2 according to the code. I can either change the help comment or change the logic. Which is preferred here ? 

should work:
noms log --color 2 http://demo.noms.io/cli-tour::sf-film-locations

does work: 
noms log --color 0 http://demo.noms.io/cli-tour::sf-film-locations

Happy to tackle this either way

**Comment by mikegray** [comment]
@willhite is probably the right person to answer

**Comment by willhite** [comment]
I think the only thing that needs to change is the help message here. It look like '--color 0' forces the color off, and '--color 1' forces it to be on. That seems like the right behavior to me. Feel free to fix, @zcstarr

**Comment by zcstarr** [comment]
merged in https://github.com/attic-labs/noms/pull/2520
