### ISSUE TITLE
idea: `merge` command

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2445]
It would be cool to be able to interact with merge a bit to be able to figure out how to work it into our command set. Also, it would make a great demo. To that end, I propose:

```
noms-merge <left> <right> <ds-out>
```

This wouldn't be part of the `noms` binary (yet), just a standalone sample program. It merges the values at `left` and `right` using our currently in-progress merge policies and writes the result to `ds-out`.

In the case of conflict, noms-merge enters an interactive mode that looks like:

```
!? noms-merge http://localhost:8000::foo.value http://localhost:8000::bar.value http://localhost:8000::baz
merging....

Conflict at: .value[42].firstName
Left: "Samuel"
Right: "Simon"
Enter 'l' to accept the left value, 'r' to accept the right value, or 'c <val>' to enter a custom resolution.
```

**Comment by rafael-atticlabs** [comment]
closing in favor of #2535 which more accurately describes the work to be done.
