### ISSUE TITLE
Google groups permissions problems

### ISSUE THREAD

**Issue by mikegray** [attic-labs/noms#2451]
Visit https://groups.google.com/forum/#!forum/nomsdb when logged in to Google as your Attic Labs account. It works fine.  Now logout of Google and try to access the same link again with a different Google account.  You will receive a "You do not have permission to access this content. (#418)" error message.  I looked at the group settings and it appears to be "public".  Not sure what settings need to be modified to fix the issue.

**Comment by mikegray** [comment]
This was reporting on Noms Slack #general channel by @michael. When fixed, please consider sending a message to that channel and including his username to let him know it is fixed.

**Comment by aboodman** [comment]
Fixed.
