### ISSUE TITLE
Panic on invalid ldb-max-file-handles argument

### ISSUE THREAD

**Issue by zcstarr** [attic-labs/noms#2454]
Summary:
If ldb-max-file-handles is set to 0 or -1 , csv-import will hang indefinitely or panic. ldb-max-file-handle should be checked for being > 0, and if the value is in violation of this condition, it should return an Error and exit.

Repro:
`csv-import nameof.csv  /tmp/test::nameoftestds --ldb-max-file-handles -1`

`csv-import nameof.csv  /tmp/test::nameoftestds --ldb-max-file-handles 0`

**Comment by zcstarr** [comment]
This occurs for the csv-export tool as well

**Comment by aboodman** [comment]
We don't have ldb anymore.
