### ISSUE TITLE
Add Path specifier for selecting type

### ISSUE THREAD

**Issue by mikegray** [attic-labs/noms#2463]
I think it would be useful to be able to get the type information for a given path specification.  For example, I wanted to iterate through all of the datasets we have on demo.noms.io and see what the root values were to see if we had any datasets with a map<struct, anything>. (btw, we don't currently) I could see this being useful for pipeline operations potentially too - e.g. get me the root type of a nomsfs dataset.

We have `.` for selecting fields in structs. We have `[` and `]` for specifying indices into collections. We have `@key` for selecting the key from the specified indexed item.  We have `#` for specifying a hash value.  Maybe `@type` at the end of the specification could work?

**Comment by aboodman** [comment]
Agree. we have also talked about `@ref`.

**Comment by aboodman** [comment]
Whoops dupe of #2859 .
