### ISSUE TITLE
sync seems to sync too much

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2477]
```
noms!? noms sync http://demo.noms.io/cli-tour::ny-vehicle-registrations http://localhost:8000::ny-vehicle-registrations
Done - Synced 26 GB in 55m42.74s (7.9 MB/s)

noms!? du -h /tmp/noms
3.8G	/tmp/noms
```

cc: @cmasone-attic

**Comment by cmasone-attic** [comment]
I agree that 26 gigs seems like wwwwwaaaayyyy too much data for this dataset, but I think we need to stop considering disk space as the canonical "size" of a dataset and build some little tool to determine it somehow. Data is compressed on disk, and type info is actually a pretty significant amount of noms Chunk data when it's all decompressed in RAM.

**Comment by aboodman** [comment]
agree

**Comment by rafael-atticlabs** [comment]
We could create a simple tool which `walks` (ignoring duplicate chunks) and reports the total uncompressed chunk bytes size.

**Comment by rafael-atticlabs** [comment]
But something does smell fishy about this. If anything the total byte sent across the wire should be less than the total bytes stored on disk because over the wire, we compress chunks together in batches (and thus probably get better compression).

So at worst, 55m is rough ~1.15 MB/s or ~9.2 Mb/s and the raw downstream bandwidth at the office is about 30Mb/s.

**Comment by cmasone-attic** [comment]
over the wire, yes. Reported by sync, no. Remember, sync reports uncompressed chunk sizes, so they'll always be bigger than the data on disk.

**Comment by rafael-atticlabs** [comment]
my calculus was ignoring the reported amount of syncd data. i was estimated the amount of data syncd over the wire and dividing by number of seconds the command took.

**Comment by aboodman** [comment]
Adding this to list of potential-next-halpern-tasks.

**Comment by rafael-atticlabs** [comment]
Ok, i've verified that on average the chunks are compressing down to ~14% of their uncompressed size which basically explains the 26 vs 3.8 numbers (if you just do `noms show`, you can get an intuitive feel for this. basically each chunk is encoding all of that type & struct field information for each struct instance)

There's still kind of a mystery of why we can't saturate a downstream network link, but I'm going to close this and open a different bug

**Comment by rafael-atticlabs** [comment]
Actually, doing the math again, i'm unsure there's any problem.

From my laptop, `speedtest.com` reports 22Mb (2.75MB) downstream.
From the same laptop, I can sync that dataset and it seems to steady state at around 15MB/s reported. If we apply the compression factor of `.14`, that's (2.1MB), so it's not fully saturating, it's also kind of in the ballpark.

Presumably there are things we can do in the future to pick off that remaining 25%, but it doesn't seem like a burning issue. In the near term, I think #2476 is probably lower hanging fruit.
