### ISSUE TITLE
Samples won't install unless noms/js is installed first

### ISSUE THREAD

**Issue by zcstarr** [attic-labs/noms#2483]
Summary:
Checking out noms and then npm installing from samples does not work. There is an implicit dependency on noms/js . 
Should we 
a) list this in docs or 
b) detect the missing dependency and attempt to install it .

**Comment by arv** [comment]
This should be documentated already.

**Comment by arv** [comment]
We could detect it and show a friendly error message

**Comment by sunglim** [comment]
Probably, with [script property](https://docs.npmjs.com/misc/scripts) of package.json, we can add a script that checks the existence of `/noms/js/node_modules` directory. and show a friendly error message.

I'll try

**Comment by rafael-atticlabs** [comment]
n/a
