### ISSUE TITLE
Kill CodePipeline

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2501]
It gives us lots of trouble. Let's try and find a way to use just jenkins+codedeploy (via the aws command line).

**Comment by arv** [comment]
I'll look at transition splore and perf to CloudFront....

**Comment by mikegray** [comment]
Seems like it would make sense to host the pre-built Noms binaries in S3/Cloudfront too - #2306

**Comment by arv** [comment]
Splore and Perf Viewer have both migrated off CodePipeline

**Comment by aboodman** [comment]
\o/

**Comment by mikegray** [comment]
The Jenkins NomsMasterBuilder and the NomsBuildGoBinaries do not use AWS CodePipeline. Maybe the only remaining pieces here are the DemoServer build and deployment to demo.noms.io?

**Comment by arv** [comment]
Yup. The  only remaining thing is DemoServer. I think we can use AWS CodeDeploy directly from Jenkins but only looked at it briefly.
