### ISSUE TITLE
(JS) Auto-merge concurrent commits to noms datasets

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2524]
Currently a noms database has zero concurrency. Even commits to separate datasets must be serialized.

Now that we have auto-merge, we should take the first step of adding back some concurrency by allowing concurrent commits on separate datasets to auto-merge.

**Comment by aboodman** [comment]
That is, currently:

```
ds1 := spec.GetDataset("http://localhost:8000::ds1")
ds2 := spec.GetDataset("http://localhost:8000::ds2")

ds1.CommitValue(types.NumberValue(42))

// This fails, because ds1 beat us to the punch.
// It should succeed by way of auto-merge (the two concurrent modifications to the dataset map
// should be merged).
ds2.CommitValue(types.NumberValue(43))
```

I don't think that we should go farther and allow any merging of values _inside_ the datasets right now.

**Comment by rafael-atticlabs** [comment]
Just to be clear, this isn't about auto-merging concurrent changes to the same dataset? Just about removing the weirdness from Dataset.Commit that you can get a optimistic lock failure even though  no one moved the dataset you are trying to commit to behind your back?

**Comment by aboodman** [comment]
Yes, this is just step 0.5.

We need a separate bug with a proposal for what to do about conflicts inside datasets.

**Comment by cmasone-attic** [comment]
Given our conversation today, should I dup this into #148?

**Comment by aboodman** [comment]
If you want to think of #148 as a meta-bug, then this bug is a component of
that one. However you would like to track it is fine.

**Comment by cmasone-attic** [comment]
Should keep this open for JS impl

**Comment by rafael-atticlabs** [comment]
The remaining work here is to impl in js
