### ISSUE TITLE
Move noms-merge into `noms commit` tool

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#2535]
The new interface will be:

```
noms merge [--policy=l|r|a] [--out-ds-name=<name>] [--parent=<obj>] <db-spec> <left-obj> <right-obj>

  <db-spec>   : database in which named datasets live
  <left-obj>  : path to an object descending from <parent>
  <right-obj> : path to an object descending from <parent>

See Spelling Objects at https://github.com/attic-labs/noms/blob/master/doc/spelling.md for details on the <db-spec>, <left-obj>, <right-obj> and --parent arguments.

Flags:

--policy
    If unset, any merge conflict is fatal. Can be set to one of 'l', 'r', or 'a' which will resolve conflicts by choosing the Value from <left-obj>, <right-obj>, or asking the user respectively
--out-ds-name (= "")
    output dataset to write to - if empty, defaults to printing the hash of the merged object to stdout
--parent (= "")
    common ancestor of <left-obj> and <right-obj> (required unless left-obj and right-obj are Datasets)
--quiet  (= false)
    silence progress output
```

**Comment by cmasone-attic** [comment]
@aboodman The above is the current, desired API, right?

**Comment by aboodman** [comment]
Hm, the idea of this creating its own commit seems in conflict with factoring out `noms commit`. But it's required in the case where the inputs are datasets, if you want to reflect the merge by having two parents in the merge commit.

**Comment by aboodman** [comment]
Ideas? @rafael-atticlabs ?

**Comment by cmasone-attic** [comment]
I mean...it can still craft the merge Commit and emit the hash of that object. Then noms commit just needs to understand what to do if it sees that the hash is already a Commit?

**Comment by aboodman** [comment]
I mean what metadata will it put there?

**Comment by cmasone-attic** [comment]
hm. true. Open to ideas :-)

**Comment by aboodman** [comment]
Also it wont actually work with `commit` because commit (as currently being
implemented) because both tools think they are the ones doing the commit.

**Comment by cmasone-attic** [comment]
POR: `noms commit --merge` or similar. I'll flesh out what the command line args should look like once I look at noms commit in more detail
