### ISSUE TITLE
Allow merging across databases

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#2536]
Merging currently only works within the same Database. We should remove this restriction, but it means that the merge code needs to be careful when merging collections from one database into another

**Comment by aboodman** [comment]
Should we remove it? Why?

**Comment by cmasone-attic** [comment]
The P0 label, I assume? In general, if I have an issue that's blocking a P0, I make it a P0, and earlier today I considered this as a blocker for finishing out `noms merge`.

I was considering this blocking `noms merge` prior to our conversation right before I left today because, otherwise, you had to specify a database on the command line and then paths and datasets within that DB in order to merge stuff. It seemed to me that that restriction would feel artificial and awkward to users. Now that we're re-examining exactly how to drive merging from the command line, I think this is probably not a P0 right now.

**Comment by cmasone-attic** [comment]
Not gonna do it. Wouldn't be prudent. Not gonna do it. Thousand points of light.
