### ISSUE TITLE
Noms versions?

### ISSUE THREAD

**Issue by arxpoetica** [attic-labs/noms#2541]
You aren't tagging any versions yet in GitHub. (https://github.com/attic-labs/noms/releases)

`noms version` yields a plain old `7`. What are the plans for versioning moving forward. It would be nice to have more fine tuned version specifics, with a changelog, and so forth to know what's what and have a clearer path forward/vision on upgrades and so forth.

Semver? http://semver.org/

**Comment by aboodman** [comment]
This is covered to some extent here:

https://github.com/attic-labs/noms/blob/master/README.md#status

The '7' that you see in `noms version` is the _format version_, which is different than the binary version or api version. It will change very rarely.

For API versioning, we label PRs that introduce breaking API changes:

https://github.com/attic-labs/noms/issues?q=label%3AAPIChange+is%3Aclosed

**Comment by arxpoetica** [comment]
I'm going to have to come back to this to ingest, but knee-jerk reaction (:P) it seems a little optimistic to say that a format version won't change often. I'll come back to this when I get a chance, on the other points.

**Comment by aboodman** [comment]
By very rarely, I mean sort of like the frequency of a database system's major version changing. Maybe ~once/yr or so I'd guess.

**Comment by arxpoetica** [comment]
Okay, that makes sense.
