### ISSUE TITLE
Support // spec prefix for http(s) shorthand in JS

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2551]
I propose supporting `//` as shorthand for `http://` or `https://` in the JS spec, where the scheme is given by the current page's protocol.

I.e. a URL like `https://perf.noms.io/?ds=//demo.noms.io/perf::master/csv-import` is equivalent to `https://perf.noms.io/?ds=https://demo.noms.io/perf::master/csv-import` and likewise `http://.../?ds=//demo.noms.io/...` is equivalent to `http://.../?ds=http://demo.noms.io/...`.

Rationale:
- More convenient than typing http(s) in URLs. Similar to how we don't require the `ldb:` prefix in the Go SDK.
- Automatically consistent http vs https. Chrome doesn't like crossing the schemes.

The spec code would need to ignore this if it's running in Node, of course.

@arv @aboodman opinions?

**Comment by arv** [comment]
Seems reasonable to me

**Comment by aboodman** [comment]
Gotta be honest, Im not a fan of these kind of micro-shortcuts. To me, the complexity of having to understand these extra cases doesn't pay for the value of not having to type 'http[s]:', especially since in JS, the common case is that the spec is going to be in a constant somewhere and typed once, not over and over.

**Comment by kalman** [comment]
> the spec is going to be in a constant somewhere and typed once, not over and over

This isn't true in 100% of our web samples: perf, splore, and bar-chart. They all take the DB as a URL param. I am consistently accidentally typing in https instead of http and vice versa, and the failure case is a white screen.

This was actually the motivation for filing this issue, the convenience is a nice side-effect. I expect code that hard-codes its database will look like:
```
const DB = '//demo.noms.io';
...
let db = location.protocol + DB;
```

**Comment by aboodman** [comment]
Why not always type https?

**Comment by aboodman** [comment]
I think in any case we should probably hold on this until @ehalpern's stuff is done since that will probably change how we interact with specs on the command line.

**Comment by mikegray** [comment]
Drive by comment - `//` reminds me of a samba mount, which might be `\\` but is sometimes flipped depending on if you are on Microsoft Windows or on a *nix platform.  

Not specifically for this reason, but I am mostly against `//` shorthand for `http[s]`. It is better to specify exactly what you want than have magic occur. What if `http://foo` and `https://foo` are different? Craziness.

 I would also stipulate that `perf` and `splore` are not *normal* cases for JavaScript apps.

**Comment by arv** [comment]
@mikegray `//server.com/` is a valid relative URL. It is commonly used on the web to preserve the protocol.


However, I think @aboodman convinced me that we do not need this extra complication at this point.

@kalman We should make these apps report user visible errors when the input data is not correct.

**Comment by kalman** [comment]
> We should make these apps report user visible errors when the input data is not correct

AFAIK there is no way for an application to catch when chrome blocks a connection due to mismatching http/https schemes.

**Comment by kalman** [comment]
> Why not always type https

Hm ok well if there is no issue (warnings, errors) fetching from https URLs from an http page then yes this would be fine

**Comment by arv** [comment]
Fetching https from http always work. The other direction does not work.

**Comment by arv** [comment]
> AFAIK there is no way for an application to catch when chrome blocks a connection due to mismatching http/https schemes.

I'm pretty sure you get an exception with XHR and rejected promise with fetch.

**Comment by kalman** [comment]
> I'm pretty sure you get an exception with XHR and rejected promise with fetch.

I hope it's plumbed up from the chunk store then.
