### ISSUE TITLE
Implement pipelined .map, .filter, and .reduce for JavaScript collections

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2559]
I think that this is something we're going to need relatively soon on a number of different paths.

I've put this down for JS both because it's more relevant for UI, but also because it seems like one of those things that will be easier to reason about in JS, and then "backport" to Go.

Note that unlike with basic in-memory JavaScript collections, unless care is taken, chains like `lst.map(fn1).filter(fn2).map(fn3)` become much more expensive than the `4n` that is implied (because the list gets rechunked, repersisted, and rebuilt at each link in the chain).

It seems like there ought to be a way to pipeline the operations. What you're trying to achieve is that the above chain actually gets transformed into something where you're doing one pass over the source list and one write to the destination, and all the transforms get applied at once.

I assume this is already well-studied and understood somewhere in the FP lore.

Maybe part of it is that `List.map(T => U)` actually returns `List<Promise<U>>` rather than `Promise<List<U>>`, but that doesn't seem complete.

**Comment by aboodman** [comment]
@rafael-atticlabs, @kalman, @arv: i think this is coming up.

**Comment by rafael-atticlabs** [comment]
I believe that https://www.usenix.org/system/files/conference/nsdi12/nsdi12-final138.pdf is abstractly related to this. In particular the notion that transforms are treated as a DAG of steps which are lazily computed, "pulled" on final use, and parallelizable. Note the table of compositional primitives they implemented to handle a broad set of transformations (including table joins, etc...).

**Comment by kalman** [comment]
Haskell uses "stream fusion" to collapse functional operations like this. Some docs I found:
* https://pdfs.semanticscholar.org/64d2/a65a7d559f9b05570fb0fea8bb4cccd83ae2.pdf
* http://www2.tcs.ifi.lmu.de/~senjak/haskellbeatsc.pdf
