### ISSUE TITLE
IndexedDB chunkstore

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2602]
We should bring this back for people who would like to use Noms persistently in the browser.

**Comment by joeblew99** [comment]
i was just thinking this too.

At the moment people use pouchdb and other things to enable offline first apps, but sync back to the server is less than stellar in terms of options, and couchbase is pretty tough to work with IMHO.

Also, the other thing is that as a golang developer i would have two choices for my Desktop and Mobiles apps too. I could use noms compiled with gomobile, with a webview Or IOS / Android Client OR i can use noms purely at the JS level within a webview. Thats a pretty cool bag of tricks to have !

And lastly i can use gopherjs and bind to the JS NOM OR to the golang noms.

I guess you need to abstract a file system into a indexeddb, which is not a huge feat.

Anyway, i want to register my interest in this. It would solve allot of issues and really lots of options.

i can also image noms working really well with a Kappa based architecture too.
http://milinda.pathirage.org/kappa-architecture.com/

**Comment by rafael-atticlabs** [comment]
js noms is now gone.
