### ISSUE TITLE
TodoMVC demo

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2603]
Rafael has a port of TodoMVC to Noms here: https://github.com/rafael-atticlabs/noms/tree/wunderlist. We should finish this up and land it in the samples/js directory.

Note that Raf's branch only works if you first import data from wunderlist. I think for ease of use we should remove that restriction and allow TodoMVC port to just work as a standalone application.

The wunderlist import / compat is cool and could be seen as an additional component of the sample.

**Comment by rafael-atticlabs** [comment]
I think this would be a cool to include as a demo using GraphQL<->Noms

**Comment by rafael-atticlabs** [comment]
nope
