### ISSUE TITLE
Idea: Improve sync speed by only writing to disk chunks of height > 1

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2620]
We store chunks on disk so that we can write in bottom up order, but there's actually no direct need to store the leaf sequences, only to read them back out again.

Related, @ahl was asking about why syncing from `a` to `b` on `c` required disk space on `c`. Making this change would at least dramatically reduce the amount of disk space required on `c`, and probably also speed up syncing in general.

**Comment by aboodman** [comment]
I think in general it is kind of "weird" to sync from `a` to `b` via `c` because by definition you're going to have double the network overhead. But it's also kind of neat that noms can do it and that it just falls out of the design. So I guess I support improving this as a low priority.

**Comment by rafael-atticlabs** [comment]
Note that doing this would also benefit the case of "pushing" and "pulling", because it both cases, we write locally (at the node that is doing the work) all of the data before moving it to it's final destination. doing what I suggest above has the potential to change `all` to `~2%`.

**Comment by rafael-atticlabs** [comment]
Closing in favor of https://github.com/attic-labs/noms/issues/3181
