### ISSUE TITLE
Proposal: `noms pump`

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2627]
[wip - this isn't ready for serious feedback yet]
# Problem 1

It's really common when working with Noms to want to setup "pipelines" of programs that feed one into the next.

For example we currently have running on demo.noms.io many instances of an adhoc 2-stage pipeline in which the first stage sucks down a particular csv blob, and the second stage parses that csv. In a few cases, we also have a third stage where we index that csv using `nomdex`.

Right now these pipelines are totally adhoc. We arrange them in `crontab` such that the first stage runs on the 0th minute every hour, the second stage on the 5th minute, and so-on.

It would be nice to have a little bit more structure - to be able to declare "continuously replicate dataset x to dataset y via job z", and have some infrastructure that makes sure that happens.
# Problem 2

Relatedly, it would be nice if these transforms didn't have to redo all the work everytime -- if they could work incrementally.
# Proposal

Introduce a new subcommand to noms:

```
noms pump [--incremental] <db> <source> <dest> <via>

example:
noms pump http://localhost:8000 csv/raw csv/parsed $HOME/bin/csv/read
```

The job of `pump` is to ensure that for each commit in a _source dataset_ there is a corresponding commit in a _destination dataset_ transformed by a particular _job_.

**Pump is stateless** in that each time it runs it looks at its inputs, the source dataset, and the destination dataset, and does whatever work it needs to in order to achieve its invariants, then exits. Thus it can easily be run as part of cron.
## Incremental Mode

TODO
# Implementation Handwavery

**Comment by sandalwing** [comment]
> Implementation Handwavery

Heh.

This looks really cool.

How did you envision the ingest / pipeline pieces working?  Some kind of plugin which gets invoked and fed data via STDIN, outputting to STDOUT, etc.?

**Comment by aboodman** [comment]
I'm not sure, we've gone around on that a few times. STDIN/STDOUT is always a common instinct people have because unix. But at least the way we end up doing it in practice is that we tend to use datasets as temporary storage between pipeline stages.

So for example, what we are currently doing for the data on demo.noms.io/cli-tour is something like:

```
0  *   *   *   *   url_fetch http://data.com/blah.csv http://localhost:8000::blah/raw
5  *   *   *   *   csv-import --dest-type='map:0' http://localhost:8000::blah/raw http://localhost:8000::blah/parsed
10  *   *   *   *   nomdex up --in-path=http://localhost:8000::blah/parsed --out-ds=blah/by-foo --by=.foo
```

But this is all very squishy. It is possible for there to be races or for transformations that should have run to get dropped. But I think the basic idea of using datasets as the links in the chain makes more sense than stdin/out for a variety of reasons (mainly the data can be huge and it's also not really line-oriented).
