### ISSUE TITLE
Prototype docker-based importers for Go and JS

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2635]
I don't know docker that well, but I have a feeling that there exists (or could be made) a "golang+git" docker container that allows one to do something like:

```
docker run https://github.com/attic-labs/noms/samples/go/url-fetch http://data.gov/foo.csv http://localhost:8000::foo/data
```

... and what it would do is clone that repo with git, build it as a go binary, and run it with the arguments specified.

If we had this, it would form the basis of generic 3rd-party importers.

**Comment by sandalwing** [comment]
You want something like:

```console
$ echo 'FROM golang:alpine                                                                                                             

RUN apk add --no-cache git
ENV SAMPLE url-fetch
RUN go get -u github.com/attic-labs/noms/cmd/noms
RUN go get -u github.com/attic-labs/noms/samples/go/${SAMPLE}

ENTRYPOINT ["url-fetch"]' | docker build -t noms/import -
...
Successfully built dc8a89534ed1
```

to use: (warning will consume 130MB down)

```console
$ docker volume create --name nomsdata
$ docker run -ti noms/import \
    -v /data
    "https://s3.amazonaws.com/ed-college-choice-public/Most+Recent+Cohorts+(All+Data+Elements).csv" \
    ldb:///data::foo
```

then you can followup with volume:

```
```

**Comment by aboodman** [comment]
Cool, thanks for the start.

**Comment by aboodman** [comment]
@zcstarr - this might be relevant to your interests.

**Comment by aboodman** [comment]
I'm going to close this in favor of more specific things.
