### ISSUE TITLE
Clients don't correctly handle back pressure error.

### ISSUE THREAD

**Issue by vinibaggio** [attic-labs/noms#2640]
I have one dataset in DynamoDB that I am trying to sync to another. The target dataset is completely empty. When I try syncing one to the other, I get a crash (for context: I expose noms via HTTP, using the demo server in this repo, so maybe the bug is in there, due to AWS security rules). 

If I use `noms sync` to sync to ldb locally, it works. But when I try to move the same dataset from ldb to a different dataset in DynamoDB (exposed by demo-server), I get the same crash.

Using go 1.7.1.

```
$ noms sync http://server-a:9000::index http://localhost:9000::index
        Error Trace:    s)panic:
    Error:      Received unexpected error "unexpected EOF"


goroutine 1605 [running]:
panic(0x44d940, 0xc4304980d0)
    /usr/local/Cellar/go/1.7.1/libexec/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/noms/go/d.panicker.Errorf(0x4ffdb1, 0x21, 0xc435ff60c0, 0x3, 0x3)
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
github.com/attic-labs/noms/go/d.(*panicker).Errorf(0x75d908, 0x4ffdb1, 0x21, 0xc435ff60c0, 0x3, 0x3)
    <autogenerated>:2 +0x7e
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.Fail(0x71a040, 0x75d908, 0xc43389e660, 0x2a, 0x0, 0x0, 0x0, 0xc420014140)
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:225 +0x510
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.NoError(0x71a040, 0x75d908, 0x719f40, 0xc420014150, 0x0, 0x0, 0x0, 0xc420014150)
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertions.go:839 +0x124
github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert.(*Assertions).NoError(0xc420014650, 0x719f40, 0xc420014150, 0x0, 0x0, 0x0, 0x719f40)
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:205 +0x69
github.com/attic-labs/noms/go/datas.deserializeHash(0x71ae00, 0xc436b9b840, 0x0, 0x0, 0x0)
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/datas/serialize_hints.go:67 +0x105
github.com/attic-labs/noms/go/datas.deserializeHashes(0x71ae00, 0xc436b9b840, 0xc436b9b840, 0x71ae00, 0xc436b9b840)
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/datas/serialize_hints.go:59 +0x166
github.com/attic-labs/noms/go/datas.(*httpBatchStore).sendWriteRequests.func1(0xc42001a150, 0xc420017ef0, 0xc420017e90)
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:416 +0x689
created by github.com/attic-labs/noms/go/datas.(*httpBatchStore).sendWriteRequests
    /Users/vinnyfuentes/code/golang/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:422 +0x91
```

**Comment by vinibaggio** [comment]
Let me know if I can help with more info on debugging this issue!

**Comment by aboodman** [comment]
@rafael-atticlabs, @cmasone-attic

**Comment by aboodman** [comment]
Is localhost:9000 in that example demo-server? I would have expected to see `?access-token=xxxxx` in the URL if so, where `xxxxx` matches the value passed to `demo-server -authkey=`.

**Comment by vinibaggio** [comment]
Ah yeah, I modified the demo server to remove the auth-key. Apologies, it's not the exact same code, but it's largely based on it.

**Comment by vinibaggio** [comment]
Is there an alternative way to expose a dataset that lives in DynamoDB? It's been a long time since when I set it up for the first time :)

**Comment by rafael-atticlabs** [comment]
I looked into this with @vinibaggio and confirmed the root cause was dynamo telling the noms server to back off. The code attempts to return to the client the set of unwritten chunks, but the noms client just crashed trying to deserialize this.

At a higher-level, this backpressure mechanism isn't obviously consistent with the way writing works now (i.e. *not* batched). It might make more sense to just tell the client "try again later" (as opposed to trying to reason about *some* of the write having succeeded).

@cmasone-attic ?

**Comment by rafael-atticlabs** [comment]
Note that vinny has a work-around for this (increase the provisioned read/write load for his DDB table), so this isn't a burning fire.

**Comment by rafael-atticlabs** [comment]
This has never been fully piped through the system and is basically a half implemented. We should remove it unclear there's a clear enough need to finish a design.
