### ISSUE TITLE
paths: it should be possible to index into sets by position

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2676]
Right now in the path system, you can index into sets by key, like if you have the set `{"foo", 42, #4niqn6lu9kuq6i35ovq26vqfaov60vs3}`, you can say: `myds.set[#4niqn6lu9kuq6i35ovq26vqfaov60vs3].thinger`.

But it would be more useful in everyday practice to be able to index by position, e.g., `myds.set[2].thinger`.

**Comment by kalman** [comment]
I think this is https://github.com/attic-labs/noms/issues/1941
