### ISSUE TITLE
Add --hide-type option to noms show

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2694]
I've mentioned this before and had a lukewarm response, but viewing raw picasa data is a huge pain in the ass because the type information is so massive. I really need this.

**Comment by aboodman** [comment]
Is the fact that the type info is so massive a problem in itself?

**Comment by kalman** [comment]
Potentially yes. I need to page through about 5K lines to actually get to data. The reason it's so big is that it's an enormous union (even when I print out the value, not the commit object). Optional types might help here. I should actually look into why the API is giving multiple types.

@rafael-atticlabs

**Comment by aboodman** [comment]
The Go version of `jsonToNoms` has a `useStruct` field:

https://godoc.org/github.com/attic-labs/noms/go/util/jsontonoms

I wonder if what is happening is that you're using the JS `jsonToNoms` and putting some data in there that really makes more sense as a map.

Does the data you're dealing with semantically make sense as a (union of) structs or as a map?

**Comment by kalman** [comment]
Yeah, that's exactly what I'm doing - just dumping the whole response into a struct.

Long story short, it's the exif data which one may naively think is struct-like but in fact appears to be map-like.

**Comment by kalman** [comment]
Note that all of the other importers do this as well, if they include exif data they may have the same problem.

I went through our other 2 existing importers, FB and Flickr, and while they don't include exif data they do represent empty lists as nothing, so the schemas within the lists are very big. I.e. types are really big.

This is turning into a separate bug. In the immediate term I would like to view raw data though, so a --hide-type option would be handy.

**Comment by aboodman** [comment]
Here is the problem that I see with adding a `--hide-type` option: there are many other contexts in which we use HRS (`noms log`, `noms diff`, etc). Will we add `--hide-type` to all of them? This is why I would like to think of a solution to this problem which is not specific to `noms show`.

One option I can think of would be to truncate or elide long types in HRS, and be able to get the entire thing with a `@type` annotation.

**Comment by kalman** [comment]
Fair enough, though we don't show types in diff related things (diff and log).

**Comment by kalman** [comment]
I can imagine the default everywhere should be to _not_ show the type, and require a `@type` annotation. That would let you diff types, which there is no way to do at the moment.

**Comment by aboodman** [comment]
Yeah I also like that because it is solving the problem with a more general-purpose tool.

**Comment by aboodman** [comment]
See #2859 for @type path part.
