### ISSUE TITLE
Not getting conflicts when expected in JavaScript

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2707]
While investigating #2699, I was trying to simulate the conflict, and I found this more basic problem in conflict detection in javascript's database.commit():

First patch in: https://github.com/attic-labs/noms/pull/2706

Then:

```
cd samples/js/counter
npm install
```

Then run `node . http://localhost:8000::c1`  in one shell, wait a few seconds, then run same thing in a separate shell.

Here's what I see. In both shells, output is the same:

```
!? node . http://localhost:8000::c1
current value is 7
waiting 10 seconds...
done
succeeded, new val is: 8
```

What I expect is that second shell will have a conflict.

**Comment by aboodman** [comment]
Note that this is committing to same dataset both times ... so this actually should conflict.

**Comment by cmasone-attic** [comment]
This is because the code detects whether you're trying to land the same commit as is currently the Dataset's Head and, if so, lets you go ahead.

So this is working as intended. If you comment out the following in _doCommit():
```js
          if (equals(commitRef, currentHeadRef)) {
            break;
          }
```
you'll get a Merge Needed error.

**Comment by aboodman** [comment]
Ah. Makes sense. I think maybe we should take that feature out now, but
that's a separate bug.
