### ISSUE TITLE
Sufficiently long strings as keys in Maps & Sets can cause prolly tree construction to fail

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2762]
@willhite Discovered this bug constructing maps of `String<String, T>` where the keys are URLs.

The can problem can occur because internal nodes of the prolly tree chunk over the stream of bytes which is the full encoding of each `MetaTuple`, which for Maps & Sets contains the largest value in the referenced sub-tree. In the case of a long string which happens to chunk, a new `MetaTuple` is created for a parent level, and will chunk again on the same encoding of the string, and so on, until the stack explodes.

**Comment by rafael-atticlabs** [comment]
Both @kalman and I encountered a similar issue at various points working on ptree construction. Each of us hit it independently because we had lowered the rolling hash window to something like 8 bytes in an attempt to make the ptrees narrow enough to reason easily about. The problem shows up in that instance because `treeLeaves` is an eight byte value and if that happens to chunk, it'll be the same value in the parent level, and same problem.

I wish I had thought more deeply about this when I hit it ("hmm... what else could cause this behavior"), because it seems so obvious that the `key` value is in danger of the same thing...but unlike noms, I can't turn back time (wacka wacka wacka).

Thinking about it now, because prolly trees only sort by the natural order of the key in the case of scalars, we also have this danger (at least in theory with numbers), because they encode as arbitrary precision. For Noms v7, it can't occur with numbers because it's not possible to encode with anymore precision that 8 bytes, but when we fix that, the danger reappears.

**Comment by rafael-atticlabs** [comment]
I think this problem requires some group thought (I'm looking at @kalman & @aboodman, in particular).

It's tempting to want to apply a "structural" fix, for instance just limit internal nodes of ptrees to a minimum of 2 meta tuples. This would have the effect that a parent meta tuple would have a different key value.

However, my memory is that whenever we visited an idea which essentially made the decision of drawing a chunk boundary a function of something *more* than just the input bytes to the rolling hash, it tended to mean that 

- Re-chunking could "cascade" down the tree (i.e. beyond the chunk window)
- Reasoning about correctly re-chunking trees correctly became *way* harder

The second of these two worries me WAY more than the first. The re-chunking logic is already very subtle and introducing additional inputs to the chunk function would worry me alot.

At this moment, I'm tempted to feel like the most *right* answer is some form of XOR into the bytes fed the rolling hash function, some additional entropy that changes with the level of the tree.

The simplest solution seems like a repeated 8-byte encoding of the the ptree level (0 for leaf level, 1 for the internal level above that, etc...). `Height` of the ref to the level before naively seems like a candidate, but there's actually no guarantee that all of the refs in a meta tuple have the *same* height (it would still work, but it'd be more gross to implement).

**Comment by aboodman** [comment]
I'm sorry, I don't know that I can be useful without a reintroduction to rechunking. Your idea of adding bytes based on tree level seems reasonable to me as the "right" fix, but again that would be a breaking change.

**Comment by rafael-atticlabs** [comment]
Related issue here: https://github.com/attic-labs/noms/issues/2763

**Comment by rafael-atticlabs** [comment]
@aboodman. Yeah, I think the bigger challenge here may be coming up with a non-breaking hack that allows this. The minimum internal-node-value solution is appealing. maybe we can convince ourselves the we can manage the implications of re-chunking correctly.

Another thing to consider here is how to handle the next batch of format changes. I'm thinking specifically here of maybe creating explicit DEV, BETA & RELEASE branches of noms, where we might bump the format version for each change as it lands, but it'd allow users to manage the pain of upgrading data.

**Comment by rafael-atticlabs** [comment]
FWIW, if we come up with a near-term compatible hack, I'd imagine reverting it concurrent with landing the "correct" solution which bumps the version.

**Comment by aboodman** [comment]
It seems ~impossible to carry multiple branches in parallel. In Chrome we didn't do this, all work was on trunk the other branches were just for emergency fixes.

I think we should just delay the "right" fix until format 8.

**Comment by aboodman** [comment]
Sorry I misread https://github.com/attic-labs/noms/issues/2762#issuecomment-256672457 - I thought you were proposing to branch *soon* to fix this. It is an interesting question of how to actually develop a new format change and roll it out, once we get to that.

**Comment by kalman** [comment]
####  For the "right", breaking change:
Adding entropy to the chunker seems like the right thing to do. It's the most consistent with how probability works. XOR over the bytes fed into the rolling hash seems the best logic way to do this - though it would be better as the *subtree ref* I think.

Like, for a meta sequence, instead of feeding:

```
Ref1 + Key1 + Size1 + Ref2 + Key2 + Size2 + ...
```

we feed:

```
Ref1 + XOR(Ref1, Key1 + Size1) + Ref2 + XOR(Ref2, Key2 + Size2) + ...
```

Height would probably work but the entropy won't be particularly good:

```
XOR(00000001, Key1 + Size1)
XOR(00000010, Key1 + Size1)
```

etc. I presume that's how our number encoding works, at least.

Plus like @rafael-atticlabs mentioned it's more ambiguous - there is no concept of prollytree height, only ref height, and this can be different for each meta tuple if their refs are different heights. E.g. `List<[42, Ref<42>]>`.

(Incidentally, either way there is a layering issue, since the chunker only knows about bytes, not what those bytes represent, so it doesn't know which part is the ref. Seems easily solvable though.)

#### For a temporary, mostly-non-breaking change:
I think we could get a mostly-non-breaking change here if we did something similar to the "right" change, but only for the bytes of the meta tuple key past the end of a chunk window:

```
Ref1 + SpecialXOR(Ref1, Key1 + Size1) + Ref2 + SpecialXOR(Ref2, Key2 + Size2) + ...
```

Where `SpecialXOR` is implemented like:

```go
func SpecialXOR(ref byte, bytes []byte, rv *hasher) {
  for i := hashWindowSize; i < len(bytes); i++ {
    bytes[i] = bytes[i] ^ ref
  }
  hashValueBytes(bytes, rv)
}
```

This would break backwards compatibility with maps that have very long keys, but that should only be a very small number at this point.

#### For a temporary, definitely-non-breaking change
I think you could modify the mostly-non-breaking change to be definitely-non-breaking by changing `SpecialXOR` to only affect chunks which we definitely know will cause this infinite chunking behaviour... which I think is by adding the condition that it *will* chunk? Like:

```go
func SpecialXOR(ref byte, bytes []byte, rv *hasher) {
  if len(bytes) < hashWindowSize {
    hashValueBytes(bytes, rv)
    return
  }

  rv2 := *rv
  hashValueBytes(bytes, rv2)

  if !rv2.crossedBoundary {
    // Didn't cross boundary, fine to continue.
    *rv = rv2
    return
  }

  // Key was longer than hash window, and it crossed a hash boundary.
  // It will always chunk, therefore crash on construction, so introduce
  // entropy so that it might not chunk.
  for i, b := range bytes {
    bytes[i] = b & ref
  }
  hashValueBytes(bytes)
}
```

In fact I like kind of prefer that... I think it works?

**Comment by rafael-atticlabs** [comment]
@aboodman I wasn't suggesting a timing or priority for this work: just thinking through the problem. FWIW, When I mentioned DEV, BETA & RELEASE, I was (unsurprisingly) thinking precisely about how we did things on Chrome.

**Comment by rafael-atticlabs** [comment]
@willhite, is your forward progress effectively blocked by this bug?

**Comment by willhite** [comment]
No, I have a simple workaround.

On Thu, Oct 27, 2016 at 12:22 PM, Rafael Weinstein <notifications@github.com

**Comment by kalman** [comment]
Update to my idea:

Seems to work for initial chunking, but seems infeasible for re-chunking.

Also: XOR-ing with the prolly tree height (which we know about during the construction of a prolly tree, but it's not in the serialization) is the right thing to do, not the ref, my bad.

**Comment by rafael-atticlabs** [comment]
@kalman & I discussed his idea. We're agreed it would allow ptrees to be constructed that currently iloop without affecting the chunking of ptrees which could have been constructed prior (i.e. be currently stored in someones db), but neither of us is convinced it's practically possible to do this *and* retain correct ptree re-chunking (i.e. mutation).

**Comment by aboodman** [comment]
Experimental research into the commonness of this problem:
```
a 173
b 1732
c 373
d 1408
e 4540
f 183
g 224
h 3129
```

that is the length of key required of a sequence of the specified letter in order to cause the iloop.

**Comment by aboodman** [comment]
These are maps of the form:

`"a": true`, `"aa": true`, `"aaa": true`, etc.
`"b":true`, `"bb": true`, `"ccc": true`, etc.

**Comment by aboodman** [comment]
Test harness here: https://github.com/aboodman/noms-1/tree/hack

**Comment by rafael-atticlabs** [comment]
Thinking more about this bug. There are two challenges to finding a non-breaking fix:

1) Add behavior which only affects data-states which the existing bug would have previously made impossible to commit.

2) Do so in such a way that we feel good that the new data-states that are enabled can be correctly re-chunked without significant risk to breaking identity (i.e. multiple shapes of the same logical collection).

I think there are multiple ideas which achieve (1), but the re-chunking code is already very subtle, and I'm worried that it'd even be possible to achieve (2) -- meaning I'm sure we can code *something*, but feeling good that it doesn't break identity will be hard.

Especially given that #1677 is still open, it's hard to put a guess on how likely it is event that the current code is 100% correct.

**Comment by willhite** [comment]
We had another problem surface in some event loop code because of this bug. One of the urls from yahoo is causing it. I also isolated a sequence of chars that repro this problem when it is embedded into another string. Here's the program to illustrate the problem again:

```
package main

import (
    "github.com/attic-labs/noms/go/types"
)

func main() {
    s := types.NewSet()
    bad := "/github.com/attic-labs/attic/js/jobs/flickr/find-photos#76974365"
    url := "aslkghqegr91bhr39u4htbp1r-" + bad + "-qbevnipbrp2hugo3j149u13"
    s.Insert(types.String(url))
}
```
