### ISSUE TITLE
Support preservation of unnamed field values in go struct marshaling 

### ISSUE THREAD

**Issue by ehalpern** [attic-labs/noms#2795]
Problem: 

When unmarshaling a noms struct into a go struct, fields omitted from the go struct but present in the noms struct are ignored. If the go struct is then marshaled back to noms, the ignored fields are lost. 

A concrete example of this problem can be seen in the photo-dhash job which adds a dhash field to every photo object. The noms struct looks something like:

```
struct Photo {
  id: String,
  title: String 
  sizes: Map<struct, {...}, String> 
  datePublished...
  dateTaken...
  ...
}
```

The go struct looks like: 

```
struct Photo {
  Id string,
  Sizes map[struct{...}]string, 
  Dhash String `noms:"-"`
}
```

Proposed Solution:

- Define a naming convention or annotation that marks a field to hold the original noms value.
- On unmarshal, the field is set to the value read
- On marshal, the other go struct fields are merged with the original value

The new go struct would look something like this:

```
struct Photo {
  Id string,
  Sizes map[struct{...}]string, 
  Dhash String `noms:"-"`
  Original types.Value `noms:"+"` 
}
```

**Comment by ehalpern** [comment]
fyi: @arv & @willhite

**Comment by arv** [comment]
Another option might be to be able to marshal a go struct into a noms struct. Then you can extract what you need (noms -> go) and do your changes and then you can apply those changes into a new noms struct (go ->noms).

Regarding your proposal: I would not use a naming conventions. We can use a tag for this.

**Comment by ehalpern** [comment]
That's an interesting alternative. I suppose that would be the foundation of the implementation regardless.  

The drawback is that it requires the caller to do the extra book keeping rather than handle it automatically. I think there's a good chance that this will be a common pattern due to structural typing in noms.
