### ISSUE TITLE
Support optional fields in go struct marshaling

### ISSUE THREAD

**Issue by ehalpern** [attic-labs/noms#2796]
Problem: 

Suppose you want to add a field to a noms struct if it doesn't already exist using go struct marshaling. If you don't annotate the field, unmarshaling from noms -> go will fail in the 
case that the field doesn't exist in noms. If you ignore the field using `noms:"-"`, the field won't be set if it exists in noms.

Proposal: 

Introduce a new optional annotation `noms:"[noms-field-name]?"`. When unmarshaling from noms to go, an optional go field will be set if the noms field exists. When marshaling from go to noms, an optional go field will be marshaled to the noms values if its set.

**Comment by ehalpern** [comment]
fyi: @arv, @willhite, @aboodman

**Comment by arv** [comment]
I would at least do:

```go
type T struct {
        X int `noms:"abc,optional"`
}
```

On the Go side, we need to define what missing means. For `omitempty` we use zero value as well as empty collections.

**Comment by aboodman** [comment]
I defer to arv.

**Comment by ehalpern** [comment]
> I would at least do:
> ...
>        X int `noms:"abc,optional"`

OK. What is the form when a custom field name isn't needed?
```
X int `noms:",optional"`
```
 
> On the Go side, we need to define what missing means. For omitempty we use zero value as well as empty collections.

I think it makes sense for normal go rules to apply, but not certain this won't cause problems when a zero value is significant in a noms struct.
