### ISSUE TITLE
fb slurp on cron: "Cannot read property 'reduce' of undefined"

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2801]
```
TypeError: Cannot read property 'reduce' of undefined
at .../js/fb/slurp/dist/main.js:72:37
...
```
for @rafael-atticlabs fb slurping. Maybe there are no photos or something? I'll disable the cron entry for now. @aboodman

**Comment by aboodman** [comment]
Yeah i have it on my TODO list to investigate this. There definitely is data in FB for @rafael-atticlabs , but something is going wrong during find-photos.

**Comment by aboodman** [comment]
Fixed in https://github.com/attic-labs/noms/pull/2839
