### ISSUE TITLE
JS vs Go memory stores cache nil values differently

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2802]
I noticed this while writing spec tests for Go and JS.

I've found that the following JS code behaves like:
```javascript
const s = "hello";
const db = new Database(new BatchStoreAdaptor(new MemoryStore()));
await db.readValue(getHash(s)); // undefined
db.writeValue(s);
await db.readValue(getHash(s)); // "hello"
```

Whereas the equivalent Go code behaves like:
```go
s := types.String("hello")
db := datas.NewDatabase(chunks.NewMemoryStore())
db.ReadValue(s.Hash()) // nil
db.WriteValue(s)
db.ReadValue(s.Hash()) // nil
```

The difference is that the final line in the Go code returns `nil`, but I would expect it to return `s` like JS. This is pretty surprising behavior.

@cmasone-attic

**Comment by cmasone-attic** [comment]
MemoryStores are chunk stores and don't have readValue and writeValue. Can
you provide the real code that gave you this problem?

**Comment by kalman** [comment]
Example updated with real code.

**Comment by cmasone-attic** [comment]
I think this isn't supposed to behave that way. I didn't add the "value cache" to ValueStore in Go, so I'm not entirely sure if there's a reason that items aren't added to the cache on WriteValue. Still, the code should fall through and go get the chunk out of the underlying BatchStore in that case and properly return the value. I dunno what's going on here. @rafael-atticlabs it looks like you added a sizeCache to ValueStore...do you remember what's supposed to happen here?

**Comment by cmasone-attic** [comment]
I see where the buggy behavior comes from in Go, now that I look at it. The thing that JS is trading off is that it's effectively not caching non-existence. So if you try to read a value that isn't in the database over and over again in JS it'll hit the batch store every time. If you do that in Go, it hits the cache. But the cache isn't clobbered by WriteValue, and it looks like it should be -- on both sides.

**Comment by cmasone-attic** [comment]
"spoke" to Raf and we think we remember what's going on here.

Essentially, we believe that reading freshly-written Values is an uncommon use case, so we don't add them to the value cache in ValueStore.WriteValue(). The chunks that make up a newly written Value can be gotten efficiently from the underlying BatchStore anyway (either because they're local, or httpBatchStore has them cached to be sent later) so it seemed like it was a good memory-saving tradeoff to make.

The bug is that trying to read the value first, when it's not yet in the DB, causes the cache to remember that the value isn't there. The subsequent WriteValue doesn't clear that, so the caller gets stale results on subsequent ReadValues.

**Comment by kalman** [comment]
So... is there a bug here, or is this an unavoidable side effect of the "freshly-reading Values..." case?

**Comment by rafael-atticlabs** [comment]
I think the bug is that both js & go should

1) cache non-existence (when discovered) during read
2) cache-expire any chunk which is written (which, importantly covers the case of read associating nil with a given address).

(js needs to do 1 and both need to do 2), right @cmasone-attic ?

**Comment by cmasone-attic** [comment]
yes. The reason I don't have a patch posted yet is because javascript, as previously discussed, is...fuck.

**Comment by kalman** [comment]
Btw there is a `cacheSize` parameter to `new Database` in JS which does enable some caching layer.
```
...
const cacheSize = 1e6;
const db = new Database(new BatchStoreAdaptor(new MemoryStore()), cacheSize);
...
```
if that makes any difference.

**Comment by cmasone-attic** [comment]
yeah, that's the value cache we've been talking about this hwole time

**Comment by cmasone-attic** [comment]
oh
yeah, JS actually behaves just like Go does if you actually enable the cache. If you don't, then it goes to the BatchStore every time.
