### ISSUE TITLE
OID is too slow

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#2836]
The OID (order id) is only used to determine the order of union types. It has one reqiurement: it needs to be deterministic.

Currently we use a sha512 over the encoded bytes. This is very expensive when there is a deep type hierarchy since at every level where we need to compute the OID we have to serialize the whole sub tree [1].

A simpler and faster method would be to compute an OID as a function of the OIDs of the elements of the type. That way we would only need to visit each type once as we compute the OID. This would however lead to a change in the ordering of the union elements which requires a Noms version change.

[1] That is not entirely true. When we hit a union type further down we can compute the OID for its elements and cache them.

**Comment by arv** [comment]
@rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
Thanks to type simplification, we can just remove it now.
