### ISSUE TITLE
Go Set marshalling

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2842]
Our Go code doesn't support types.Set marshalling. The Go idiom for sets is `map[T]struct{}`, we should do the same, but require a struct annotation to enable it:
```go
type struct Foo {
  ID        string
  Databases map[string]struct{} `noms:"set"`
}
```
For now, we should _only_ support `struct{}` as the value type. It's the idiomatic way to do sets.

@arv

**Comment by kalman** [comment]
For supporting top-level marshalling of Sets we can have a separate function, but I was thinking, this is much less useful than having them embedded inside structs. You should just be iterating over a set if it's top level.

**Comment by arv** [comment]
https://github.com/attic-labs/noms/issues/2376

**Comment by kalman** [comment]
Fixed
