### ISSUE TITLE
Segfault in photo dhash sample

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#2849]
See https://atticlabs.slack.com/files/slackbot/F35AKF68Y/hashed_photos.value.bydate_

Not posting logs in case there is sensitive data in there.

**Comment by kalman** [comment]
CC @ehalpern

**Comment by ehalpern** [comment]
Tracked this to a race condition in encode.mapEncoder.  Here's the relevant code: 

```
func mapEncoder(t reflect.Type, parentStructTypes []reflect.Type) encoderFunc {
2-->	e := encoderCache.get(t)
	if e != nil {
		return e
	}
	var keyEncoder encoderFunc
	var valueEncoder encoderFunc
	e = func(v reflect.Value) types.Value {
		keys := v.MapKeys()
		kvs := make([]types.Value, 2*len(keys))
		for i, k := range keys {
3---->>>	        kvs[2*i] = keyEncoder(k)
			kvs[2*i+1] = valueEncoder(v.MapIndex(k))
		}
		return types.NewMap(kvs...)
	}

1-->	encoderCache.set(t, e)
	keyEncoder = typeEncoder(t.Key(), parentStructTypes, nomsTags{})
	valueEncoder = typeEncoder(t.Elem(), parentStructTypes, nomsTags{})
	return e
}
```

The first go-routine calls mapEncode and creates an encoder for a particular map type and inserts it into the cache at (1). Note that at this point, keyEncoder and valueEncoder are not set. 

A second go-routine calls mapEncode for the same type and finds it in the cache at (2). If it does this before the first routine has completed initializing keyEncoder, it will segfault at (3).

**Comment by kalman** [comment]
Wow, nice find. @arv

**Comment by aboodman** [comment]
wrongeric

**Comment by kalman** [comment]
No, it was the righteric. This is the marshal code.

**Comment by aboodman** [comment]
Oh, I misread. I thought you said "nice find @arv". But you said "nice
find. @arv". :).
