### ISSUE TITLE
Optimize struct type validation. The regexp's show in profiles.

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2866]
While doing something else, I noticed that sync appeared to have gotten slower. I bisected it and discovered that https://github.com/attic-labs/noms/commit/5e901b092401c14b36084fe9f140dc3e3a4f6a9e regressed syncing ~300MB of sf_scrime data from ldb to ldb by ~ 100%.

After some short digging, I'm fairly sure it's because of the addition of type validation to the validating_batch_sink.

Thinking about it some, I think it's an easy fix because of the type cache. Basically we're validating over and over again exactly the same in-memory type graph (the type cache ensures that identical types are interned). we just need to find a way to only do it *once* per type.

**Comment by rafael-atticlabs** [comment]
cc @aboodman to set priority

**Comment by rafael-atticlabs** [comment]
this essentially affects writing of data to a remote server (which logically includes syncing to a local ldb store)

**Comment by aboodman** [comment]
Let's just drive it by perf of attic. For example I just asked @arv to estimate difficulty of #2869 because it badly affects attic ui perf. If we find that this bug also affects perf, then fix. Otherwise no.

**Comment by aboodman** [comment]
IOW, not a prio right now.

**Comment by rafael-atticlabs** [comment]
Blocked by https://github.com/attic-labs/noms/issues/3123

**Comment by arv** [comment]
Is this still valid?

**Comment by rafael-atticlabs** [comment]
I looked recently and I kinda looked like it was. The problem is that the regex is expensive.

**Comment by arv** [comment]
Which regexp is this? The one that validates the name?

**Comment by rafael-atticlabs** [comment]
Yup. Struct and field name.
