### ISSUE TITLE
url-fetch and blob-get incompatible

### ISSUE THREAD

**Issue by ekzhu** [attic-labs/noms#2921]
The blob dataset imported through `url-fetch` cannot be exported through `blob-get`, which returns error: `error: Value at /tmp/noms::test-blob is not a blob`.

To reproduce:
```
ekzhu$ echo "random binary stuff" > testbinary
ekzhu$ ./url-fetch testbinary /tmp/noms::test-blob
20 B of 20 B written in 0s (682 B/s)...
ekzhu$ ./blob-get /tmp/noms::test-blob localfile
error: Value at /tmp/noms::test-blob is not a blob
```

Using the most recent build (2016-11-30T02:07:50)

**Comment by rafael-atticlabs** [comment]
Hi Eric,

The `blob-get` is capable of retrieving a blob from *anywhere* inside of a noms commit. You need to give it the full path to the blob value. In the case above, `./blob-get /tmp/noms::test-blob.value` will be the path to the blob as the root `Commit` struct of any noms dataset has a `value` field as the root of its graph.

**Comment by ekzhu** [comment]
Cool. Thanks!
