### ISSUE TITLE
Go read-ahead is limited by the size of the N+1 cursor sequence

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2942]
The current read-ahead approach creates a second cursor to read ahead, but because it relies on advance(), it is blocked at the end of each leaf chunk on it's parent loading the next group of leaves. in practice, this means that it can never read ahead more than about ~150 leaf chunks (or ~500k). It experiments, I was able to see read rates nearing that of the underlying disk when reading ahead closer to 8 to 16MB.

**Comment by rafael-atticlabs** [comment]
This can hurt especially bad when ptrees are narrow & tall (i.e. in the case of maps with very long keys or large values).

**Comment by rafael-atticlabs** [comment]
To be more clear about this: the *distance* we read-ahead is measured as a constant number of meta-1 nodes. The problem with this is that meta nodes can contain a varying number of leaf references. If they contain 100-200, then we'll read ahead by something like 10MB, but they can contain *far* less. This isn't really a problem for reading large blob data, because the leaf nodes will tend to be fairly wide, but it could become a problem for map data if they keys are long.

https://github.com/attic-labs/noms/issues/2763 would mitigate this problem some.

**Comment by kalman** [comment]
Read-ahead removed in https://github.com/attic-labs/noms/pull/3763

**Comment by rafael-atticlabs** [comment]
\o/
