### ISSUE TITLE
All NBS stores should share the index cache

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#2944]
Thankfully, NBS supports concurrent file access, so it's not wrong (like it was with LDB) to have multiple views on the same store open, but it's wasteful as each view has heated up a bunch of the same memory

**Comment by cmasone-attic** [comment]
We decided to focus on extending use of the index cache to file-backed NBS instead of this, right?

**Comment by rafael-atticlabs** [comment]
Yeah, that's my memory
