### ISSUE TITLE
Add test to ensure readamplification calculation makes sense

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#2947]
Now that I think about this more, I believe we need to tweak the way in which tableReader decides whether it's read too much "wasted" data. I think it might be better to express this in terms of the ratio of desired bytes to undesired bytes. The first reason is that, currently, passing 0 or 1 (which are accepted by the API) for the read amplification factor makes the code (I believe) accept any amount of read amplification. That's very counter intuitive. If the code instead was trying to enforce a ratio between desired/undesired bytes, then 0 and 1 could have a sensical meaning.

The second is that both times I've encountered this check
```golang
if fRec.offset+uint64(fLength)-readStart < tr.readAmpThresh*(readAmp+fReadAmp) {
	break // including the next block will read too many unneeded bytes
}
```
I've had to spend 20 minutes convincing myself that it's doing the right thing :-)

Whether this gets changed or not, there should definitely be tests ensuring that it behaves as desired.

**Comment by rafael-atticlabs** [comment]
I removed the readAmpThreshold. We now only have a blockSize, below which we are willing to just read any "space" between chunks
