### ISSUE TITLE
Marshal: Provide a way to marshal time.Time

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#2970]
Idea is to do add Marshaler and Unmarshaler interface

```go
type Marshaler interface {
        MarshalNoms() (types.Value, error)
}

type Unmarshaler interface {
        UnmarshalNoms(types.Value) error
}
```

Similar to how encoding/json does this:

https://golang.org/pkg/encoding/json/#Marshaler
https://golang.org/pkg/encoding/json/#Unmarshaler

**Comment by arv** [comment]
@kalman

**Comment by kalman** [comment]
The work to support this in marshal is done, but there is no implementation of marshaling time.Time. That should be straightforward it just needs somebody to go through it all and clean them up.

**Comment by kalman** [comment]
It amounts to something like:

```go
package marshalers

type Time time.Time

func (t Time) MarshalNoms() (types.Value, error) {
  return types.NewStruct("Time", types.StructData{
    "NsSinceEpoch": t.UnixNanos(),
  })
}

func (t Time) UnmarshalNoms(v types.Value) error {
  strct, ok := v.(types.Struct)
  if !ok {
    return WrongTypeError
  }
  if strct.Name != "Time" {
    return WrongTypeError
  }
  nsSinceEpoch, ok := strct.MaybeGet("NsSinceEpoch")
  if !ok {
    return WrongTypeError
  }
  n, ok := nsSinceEpoch.(types.Number)
  if !ok {
    return WrongTypeError
  }
  return NomsTime(int64(n))
}
```

**Comment by aboodman** [comment]
As long as we're in here should we pick a new not-insane representation of
time? Sorry :-/. Either seconds or ISO8601?

Can't remember why we didn't choose ISO8601 last time.

**Comment by kalman** [comment]
ISO8601 - because there are many string representations for the same time; but if we have control over the encoding (yay!) we can standardise on that. E.g. always do relative to GMT, always pad all of the 0s or whatever.

**Comment by aboodman** [comment]
Is the only reason to use 8601 so that it's pretty when you look at it in
like `noms show` and `splore` ? Because we can fix HRS to know about time.

Seconds since epoch in GMT as a bignum seems less ambiguous. But my opinion
on this is clearly suspect.

**Comment by kalman** [comment]
8601 is nice because it's the standard for these things, and it looks nice. But it has that ambiguous representation problem.

I agree basically anything is better than nanoseconds. Milliseconds is more standard, seconds is easier for humans to parse, but... milliseconds is more standard.

**Comment by aboodman** [comment]
picoseconds. jk.

One difference with 8601 is that it includes the timezone. Is that an advantage or disadvantage?

**Comment by kalman** [comment]
Disadvantage. If it's millis you can trivially get a human readable time out of that using Javascript: open dev console, type `new Date(1484006583155)`.

**Comment by aboodman** [comment]
puh-lease. cmd+l, `javascript:alert(new Date(...))`

**Comment by kalman** [comment]
Sounds like we're circling around the most reasonable solution.

**Comment by aboodman** [comment]
I still kinda like seconds. It's so unixy.

**Comment by aboodman** [comment]
Plus at a glance maybe easier to guesstimate magnitude of difference. @arv?

**Comment by kalman** [comment]
Don't make me type `new Date(148400658.3155 * 1000)`. Kidding, it's fine.

**Comment by aboodman** [comment]
```
!? date -r 1484007466
Mon Jan  9 16:17:46 PST 2017
```

just sayin

**Comment by kalman** [comment]
😳 💥 😵

**Comment by aboodman** [comment]
👌

**Comment by arv** [comment]
Just to clear. All our times are in UTC, right?

I also have to side with not using ISO8601 unless we manually enforce how we write the string(which is not unreasonable at all).

**Comment by kalman** [comment]
Yeah those unix-style times are relative to UTC.

I imagine that writing consistent strings will be hard across platforms.

**Comment by arv** [comment]
Not sure why it would be hard? It is just a datetime format call away.

Feel free to assign to me...

**Comment by kalman** [comment]
I hand-wavedly say that not every platform has the same datetime format, could be wrong.

**Comment by aboodman** [comment]
Let's use seconds.

**Comment by arv** [comment]
Second with decimals I assume?

**Comment by aboodman** [comment]
Yeah
