### ISSUE TITLE
Marshal: Rename Noms struct generated from a Go struct.

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#2972]
Strawman is to use special field in the struct with a tag:

```go
type S struct {
  IgnoreTheName `noms:"@S2"`
}
```

**Comment by arv** [comment]
@kalman

**Comment by kalman** [comment]
As discussed, using an interface actually makes more sense, and it fits in nicely with the idiom of interfaces we're introducing in https://github.com/attic-labs/noms/issues/2970

marshal package:
```go
type MarshalOptions struct {
  StructName string
}

type MarshalOptionsGetter interface {
  GetMarshalOptions() MarshalOoptions
}
```

my package:
```go
type S struct {
  Foo string
}

func (S s) GetMarshalOptions() MarshalOptions {
  return MarshalOptions {StructName: "S2"}
}
```

**Comment by kalman** [comment]
I've found one issue with this: it means that you can't cache the type of any struct which implements `MarshalOptionsGetter`. If you *were* to contrive an annotation based system for this, as suggested by OP, we could.

I don't think it's so bad, though.

**Comment by arv** [comment]
It is true that we cannot precompute the noms struct type, unless our semantics is that `GetMarshalOptions` is only called once and that that function does not depend on any instance.

**Comment by kalman** [comment]
@aboodman 

One reasonable way I can imagine doing this, with annotations, would be something like:
```go
type S struct {
  Abc string
  Xyz int

  SetsTheName `noms-global:"name=MyStruct`
}
```
(modulo naming)

**Comment by aboodman** [comment]
Right I thought that was the null hypothesis. The annotations are less
typing, but less flexible. I'm not sure which is overall better.

**Comment by kalman** [comment]
I realised we can punt on this decision because https://github.com/attic-labs/noms/issues/2970 provides a relatively straightforward workaround:
```go
type S struct {
  Abc string
}

func (s S) MarshalNoms() (types.Value, error) {
  return types.NewStruct("MyCustomName", types.StructData{
    "abc": types.String(s.Abc)
  }), err
}
```

There are a number of problems with that: needing to generate canonical struct field names, needing to update it when fields are added, the inconvenience of marshaling more complex field types.

But at least for now it's enough to unblock people.
