### ISSUE TITLE
Arguably incorrect type accretion

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2993]
```
	s := types.NewStruct("", types.StructData{
		"foo": types.NewStruct("", types.StructData{
			"bar": types.Number(42),
		}),
	})
	fmt.Println(s.Type().Describe())
	s = s.Set("foo", s.Get("foo").(types.Struct).Set("baz", types.Number(43)))
	fmt.Println(s.Type().Describe())
```

The two lines printed are the same. I expected the second to have `baz`.

Is there a reason this works this way, or it should the check here have been for type equality not subtype?

**Comment by arv** [comment]
No reason. We used to panic if we didn't use a subtype and when I changed to allow type changes the subtype behavior was carried on.

Using `Equals` would be a better approach here.
