### ISSUE TITLE
Proposal: Type Simplification

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#2995]
Noms currently uses "[Type Accretion](https://github.com/attic-labs/noms/blob/master/doc/intro.md#type-accretion)" to derive types for collections like lists, sets, and maps. For example:

```
l := NewList(Number(42))    # List<Number>
l = l.Append(String("hi"))  # List<Number|String>
l = l.Splice(0, 1)          # List<String>
```

This works fine for simple cases, but as one starts to use nested types where each level of nesting can vary, the algorithm leads to types with combinatorial complexity.

For example:

```
// age and height are optional and omitted if zero
func person(name: string, age: uint, height: uint, reports ...typs.Struct) types.Struct {
	s := NewStruct("Person", {
		name: String(name),
		reports: types.NewList(friends...),
	})
	if age != 0 {
		s = s.Set("age", Number(age))
	}
	if height != 0 {
		s = s.Set("height", Number(height))
	}
	return s
}

l := types.NewList(
	person("bob", 42, 72, person("fred", 25, 71), person("julia", 0, 60)),
	person("becca", 0, 0, person("susan", 38, 0), person("smith", 0, 70))
)
```

The type of the final list is:

```
List<struct Person {
  name: string
  age: number
  height: number
  reports: List<struct Person {
      name: string
      age: number
      height: number
    } | struct Person {
      name: string
      height: number
    }>
  } | struct Person {
    name: string
    reports: List<struct Person {
      name: string
      age: number
    } | struct Person {
      name: string
      height: number
    }
  }
>
```

This type is already quite complex it represents a total of just six items. With real data the complexity balloons quickly. We have seen examples of 16 MB types :(.

Besides the obvious performance problem, it's also just not usable. The type above is really hard to read and doesn't provide any value to users.

## Stepping back...

The purpose of type accretion is to derive "types" for noms values that classify those values usefully. Users can look at the types of large values and know something about what those values contain.

Importantly, Noms types don't communicate all possible information about the data they are attached to. They're a summary. For example, Noms just has `Number`. If you have a set of numbers that are all positive integers, Noms can't tell you that. All you get is `Number`.

Another example: in the case of structs, users can already create values whose type omits fields that the value actually has. This is necessary to allow recursive structs.

In general, any type system has to allow some precision to be lost, otherwise the types won't be smaller than the data. It's up to us to design a system that makes a good tradeoff between precision and size.

If we are willing to give up a little more precision, we can change type accretion so that it generates types that are much smaller and easier to read.

## Type Simplification

I propose that we add a new step to type accretion that runs after the current code, which I will call *type simplification*. The aim of type simplification is to reduce the number of types in unions generated by type accretion. This is done by merging similar types using the rules below.

### Refs

Ref simplification is lossless -- `Ref<T>|Ref<U> == Ref<T|U>`.

```
Simplify(Ref<T>|Ref<U>) => Ref<T|U>
```

### Lists, Sets, Maps

Container simplification is lossy because `List<T>|List<U> ⊂ List<T|U>`. However, in practice, code using Noms ends up with things like `Map<number, Set<T|U>|Set<V|W>...>` all over the place, and it's typically very useful to collapse those.

```
Simplify(Set<T>|Set<U>) => Set<T|U>
Simplify(List<T>|List<U>) => List<T|U>
Simplify(Map<K,V>|Map<L,X>) => Map<K|L,V|X>
```

### Structs

Structs are where the majority of the savings in this proposal comes from. We merge structs that have the same name and extract a shared subtype. Fields that are not shared are omitted. In the future, when we have optional types, we can add the non-shared fields back and mark them optional.

```
Simplify(T extends Struct, U extends Struct) =>
  if t.Name == u.Name:
    fields = {}
    for each common field:
      fields[name] = T.fields[name].type | U.fields[name].type
    return NewStructWithFields(t.Name, fields)
  else:
    return T|U
```

All other types are unsimplifiable.

### Recursion

The ruleset above can be applied recursively to transform a large type all at once by walking the entire type tree in post-order and applying the transform at each level.

Or it can be applied incrementally as each level of the tree is built from the bottom up.

Applying the above rules on the `Person` type above recursively would yield:

```
List<struct Person {
  name: string
  reports: List<struct Person {
      name: string
  }>
>
```

In the future, when we have optional types, it would generate:

```
List<struct Person {
  name: string
  age: ?number
  height: ?number
  reports: List<struct Person {
      name: string
      age: ?number
      height: ?number
  }>
>
```

**Comment by arv** [comment]
Experimental and no js support yet. Keeping open.

**Comment by rafael-atticlabs** [comment]
no js, indeed.
