### ISSUE TITLE
Figure out a way to run most tests under both version `stable` and `next`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3040]
Now that https://github.com/attic-labs/noms/pull/3035 landed, we'll likely want to start making some further changes and ideally we'd find out if format changes we make for `next` break other existing semantics.

**Comment by rafael-atticlabs** [comment]
cc @aboodman Thoughts?

**Comment by rafael-atticlabs** [comment]
One approach could be to allow `next` to be enabled via environment variable. Then test bots could run full test with & without NOMS_FORMAT_NEXT enabled. Then the only rub is that certain tests will need to avoid running under sufficiently old formats.

**Comment by aboodman** [comment]
> One approach could be to allow next to be enabled via environment variable.

https://github.com/attic-labs/noms/pull/3037

> Thoughts?

I don't want this to become a major (or even minor) cost to maintain two versions. What if we go farther than the env and just tag the last commit prior to v8 "v7" and fork from there if we ever (I can't imagine why) want to make patches to v7?

**Comment by rafael-atticlabs** [comment]
Effectively side-stepped. There is only one version on master
