### ISSUE TITLE
(NBS) Race in compactingChunkSource.count() can corrupt NBS manifest

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3044]
compactingChunkSource.count() should never return before the compaction is completed. The reason is that it won't know its ultimate size until compaction finishes. In particular it may return a value > 0 when the resulting table will have 0 chunks and thus shouldn't be included.

This was the bug I noticed before and ran across again tonight. The race occurs when a table is compacted which has all duplicate chunks and UpdateRoot() is invoked before compaction finishes.

The check for chunkCount > 0 passes because it returns the size of the memtable. But then the call to hash() waits for compaction which results in an empty table which then get unioned into the manifests table set. After that the manifest can never be opened because there is no table with name `0000000`.

As an aside, I noticed that when an empty table is compacted we actually write the file and remove it. We should probably avoid writing it in the first place.

**Comment by cmasone-attic** [comment]
Mmm...as more and more operations on a compacting chunk source require waiting for compaction to complete, I start to think more and more that you were right that the locking needs to move up into store.
