### ISSUE TITLE
Commits to NBS fail if root got updated by someone else

### ISSUE THREAD

**Issue by willhite** [attic-labs/noms#3089]
I have two processes:
p1 opens a database with an NBS store
p2 opens a database with an NBS store and commits
p1 tries to commit and fails because the root has been updated

this is preventing me from using NBS in the testing as I would use an HTTP store in production.

**Comment by cmasone-attic** [comment]
What's actually happening is that the nbs _Flush()_ call during the last commit is failing -- not the actual Database.Commit()

This is because we hacked Flush() in by telling NBS to UpdateRoot()...but the root has now changed

**Comment by cmasone-attic** [comment]
I'm going to put in some retrying logic with exponential backoff to address this, but also it would be nice to avoid the need for this entirely. That work is tracked in #3090

**Comment by willhite** [comment]
Now when I attempt to run the following steps using an nbs store:

1. open db and do a commit to ds1 (succeeds)
2. open second db and do a commit to ds1 (succeeds)
3. try to commit a second time using db to ds1 (panics)

Step 3 panics but is should return an error.

**Comment by rafael-atticlabs** [comment]
Can you post the panic trace?

**Comment by willhite** [comment]
Here's the trace from my test, if you want to repro you need to uncomment the lines related to this bug in the testcase:

test -v github.com/attic-labs/attic/go/eventloop/loopdata -run ^TestLoop_Commit$
=== RUN   TestLoop_Commit
--- FAIL: TestLoop_Commit (0.01s)
        Error Trace:    store.go:284
			batch_store.go:96
			database_common.go:192
			database_common.go:141
			local_database.go:35
			local_database.go:60
			local_database.go:36
			loopdata.go:134
			loopdata_test.go:177
	Error:		Should be true
	Messages:	UpdateRoot: last != nbs.Root(); 6n9qs5fdr647ea23h1v6oo9ndv04qb8s != l8itu9pa5677s1gl4vhdbf751bsb00ah
 [recovered]
        Error Trace:    store.go:284
			batch_store.go:96
			database_common.go:192
			database_common.go:141
			local_database.go:35
			local_database.go:60
			local_database.go:36
			loopdata.go:134
			loopdata_test.go:177
	Error:		Should be true
	Messages:	UpdateRoot: last != nbs.Root(); 6n9qs5fdr647ea23h1v6oo9ndv04qb8s != l8itu9pa5677s1gl4vhdbf751bsb00ah


goroutine 5 [running]:
panic(0x5cdac0, 0xc42021e1a0)
	/usr/local/go/src/runtime/panic.go:500 +0x1a1
testing.tRunner.func1(0xc420090180)
	/usr/local/go/src/testing/testing.go:579 +0x25d
panic(0x5cdac0, 0xc42021e1a0)
	/usr/local/go/src/runtime/panic.go:458 +0x243
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.panicker.Errorf(0x6e064b, 0x30, 0xc42021c280, 0x4, 0x4)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d/try.go:25 +0xa6
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/d.(*panicker).Errorf(0xa65778, 0x6e064b, 0x30, 0xc42021c280, 0x4, 0x4)
	<autogenerated>:1 +0x7e
github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.Fail(0xa20160, 0xa65778, 0x6cda0e, 0xe, 0xc4200f0d08, 0x3, 0x3, 0xc4202202e0)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertions.go:219 +0x2e5
github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.True(0xa20160, 0xa65778, 0xc4200f0b00, 0xc4200f0d08, 0x3, 0x3, 0xc420161018)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertions.go:483 +0x75
github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert.(*Assertions).True(0xc420014850, 0xc4200f0c00, 0xc4200f0d08, 0x3, 0x3, 0x5101b0f80ae5bcd5)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/testify/assert/assertion_forward.go:313 +0x5e
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs.(*NomsBlockStore).UpdateRoot(0xc420160fa0, 0x1c1a32865b9f1aa3, 0x2389480ef669f23b, 0x15aed335b25a6041, 0x7e8843287788d9ed, 0x1c2d4dc06f37616c, 0x1c1a32865b9f1a00)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/nbs/store.go:284 +0x236
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types.(*BatchStoreAdaptor).UpdateRoot(0xc42016c940, 0x1c1a32865b9f1aa3, 0x2389480ef669f23b, 0x15aed335b25a6041, 0x7e8843287788d9ed, 0x1c2d4dc06f37616c, 0x4)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/types/batch_store.go:96 +0x8e
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*databaseCommon).tryUpdateRoot(0xc4200732c0, 0xa2ab80, 0xc4201d9780, 0xc420212fe0, 0x7788d9ed15aed335, 0x6f37616c7e884328, 0xc41c2d4dc0, 0xa2ab80, 0xc4201d9780)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/database_common.go:192 +0x17d
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*databaseCommon).doCommit(0xc4200732c0, 0xc420017677, 0x4, 0xc4201dfa10, 0x3, 0x3, 0xc42019e800, 0xc420212ae0, 0x0, 0x0, ...)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/database_common.go:141 +0x432
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*LocalDatabase).Commit.func1(0xa2bae0, 0xc4200732c0, 0xc420017677, 0x4, 0xfd417f5271183de, 0xaef32121c6e21a26, 0xe2628fdd, 0x2, 0xc42019e840, 0xc4201d3f00, ...)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/local_database.go:35 +0x187
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*LocalDatabase).doHeadUpdate(0xc4200732c0, 0xa2bae0, 0xc4200732c0, 0xc420017677, 0x4, 0xfd417f5271183de, 0xaef32121c6e21a26, 0xe2628fdd, 0x2, 0xc42019e840, ...)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/local_database.go:60 +0x94
github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas.(*LocalDatabase).Commit(0xc4200732c0, 0xa2bae0, 0xc4200732c0, 0xc420017677, 0x4, 0xfd417f5271183de, 0xaef32121c6e21a26, 0xe2628fdd, 0x2, 0xc42019e840, ...)
	/Users/dan/work/go/src/github.com/attic-labs/attic/vendor/github.com/attic-labs/noms/go/datas/local_database.go:36 +0x127
github.com/attic-labs/attic/go/eventloop/loopdata.(*LoopData).Commit(0xc420165140, 0xa2bae0, 0xc4200732c0, 0xc420017677, 0x4, 0xfd417f5271183de, 0xaef32121c6e21a26, 0xe2628fdd, 0x2, 0xc42019e840, ...)
	/Users/dan/work/go/src/github.com/attic-labs/attic/go/eventloop/loopdata/loopdata.go:134 +0x259
github.com/attic-labs/attic/go/eventloop/loopdata.TestLoop_Commit(0xc420090180)
	/Users/dan/work/go/src/github.com/attic-labs/attic/go/eventloop/loopdata/loopdata_test.go:177 +0x969
testing.tRunner(0xc420090180, 0x724fc8)
	/usr/local/go/src/testing/testing.go:610 +0x81
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:646 +0x2ec
exit status 2
FAIL	github.com/attic-labs/attic/go/eventloop/loopdata	0.021s

**Comment by cmasone-attic** [comment]
Sigh. I see the problem.

In NBS, Flush() and UpdateRoot() are sort of unavoidably conflated. That means that telling an NBS store to Flush will change its internal bookkeeping about what the current root is.

Now, the Database.Commit() code pathway wants to do several things in a particular order
1) Grab the Dataset Map that Root() currently points at
2) Modify that to create a new Map that contains a new Head for some Dataset
3) Convert that new Map to chunks
4) Ensure those chunks are present in the backing store (that is, Flush())
5) UpdateRoot() specifically _from_ the Map fetched in 1) _to_ the Map created in 2)
6) If 5) fails, go back to 1) and start over

If some outside process modifies the database between 1 and 4, Flush() will (as of the other day) update the NBS layer's notion of what the current Root is to the one set by that other process. That means that 5 should fail -- but not panic. Currently, there's an explicit check in the NBS impl of UpdateRoot() to ensure that callers pass in the right thing for the `last` argument. It seems to me that that check is too draconian and we can just return `false` at https://github.com/attic-labs/noms/blob/master/go/nbs/store.go#L284

**Comment by cmasone-attic** [comment]
I also patched this into my attic repo, uncommented the code, and verified that this test passes
