### ISSUE TITLE
Commit winds up writing to NBS manifest twice

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#3090]
This is because the Database.Commit() code calls both ValueStore.Flush() (which calls BatchStore.Flush()), and BatchStore.UpdateRoot().

In NBS, both of these things logically require updating the manifest.

FYI @rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
For posterity: when we added Flush(), I was thinking that it's existence was a feature required by various clients of noms which explicitly *want* to make data durable without updating the root. For example, importing a blob which returns a hash and then using `noms commit` to create a commit which references the blob.

It'd be nice to *only* use it for that, or to remove the need for it, as in the case of AWS, it doubles the write load on the manifest table

**Comment by rafael-atticlabs** [comment]
pretty sure this is fixed now. right, @cmasone-attic ?

**Comment by cmasone-attic** [comment]
believe so!
