### ISSUE TITLE
JS: Tighten writeValue type validation before allowing direct writing to a store

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#3099]
Once #3093, the currently proposed fix for #2869 lands, a Database will be able to contain Ref<Value> objects that point to Values with a more specific type. Up until #3093, this was disallowed.

This is relevant because, when a Value gets written, the code attempts to validate it by ensuring (among other things) that any Refs contained in the value point to objects that a) exist, and b) are of the right type. Up to now, the ValueStore code has been able to perform this validation using a cache of refs that it's encountered during read and write operations. Since all Refs in the DB had specific type information about the objects they pointed to, we could guarantee that, if ValueStore had seen a Ref, it could validate any subsequent Refs pointing to that same object. Allowing `Ref<Value>` breaks that assumption.

The Go code compensates for this by being willing to read Values when needed to ensure that all Refs being written have correct type info. In JS, though, reading Values is an async operation and we realllllly want writeValue() to be synchronous. Since JS currently only supports writing data over HTTP to a Noms server that, of necessity, enforces validity on its own, it's OK to allow JS to skip over this checking for now. But, when we do enable writing to local storage in JS, we'll need to fix this.

FYI @rafael-atticlabs

**Comment by cmasone-attic** [comment]
We may be able to do this by delaying validation in JS to valueStore.flush()-time

**Comment by rafael-atticlabs** [comment]
nope
