### ISSUE TITLE
Remove noms JS implementation

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3120]
Sadly, I think it's in evidence that JS isn't a great place to be implementing a full noms client. When we embarked on the JS impl, the rational was that it was important (a) because web, and (b) because lots of JS devs.

Having traversed this path, the following problems appear to be systemic and without a clear solution:

1) The overhead of maintaining two full implementations is large. As noms has gotten more complex, this becomes more so.
2) The tool chain for the JS world generally makes life harder -- at least relative to golang. Those of us now experienced with both go & js generally find go to far more productice and porting to JS fairly frustrating.
3) Getting good perf in go has largely been a matter of controlling memory allocations. This has proven near impossible in javascript and the perf delta between the two (single core, on the machine) is now near 20-40x. We had hoped to keep it to 4x.
4) Heading towards support of react native mobile clients is proving even more challenging because the tools for homing in a specific perf problems aren't great in JS.

There are some big changes required working towards noms 8 and if we can halve the implementation work by removing JS, it's worth considering.

cc @aboodman, @arv, @cmasone-attic, @kalman

**Comment by rafael-atticlabs** [comment]
I'd like the entertain implementing GraphQL in golang as a bridge from JS to noms as the solution to this.

In this world, what we think of as noms "jobs" (which tend to read & write alot of data) would be written in golang where we can focus power on creating a pit of success. What we think of as "apps" (which tend to read/write less data, but be more latency sensitive) would use GraphQL to read, write & query data -- either directly from a server or from a local noms peer which is compiled from golang.

At least abstractly, GraphQL is a natural fit because noms data is intrinsically a DAG. In addition, it lines up very nicely with how the go marshalling works and I think there's the opportunity, if not to share a common underlying implementation, at least to cross pollenate and have both benefit.

My plan is to do some initial work in order to try to answer the key questions in whether it's a viable path.

Before I start work on vetting this path, I'll post a list of key questions we want answered.

**Comment by rafael-atticlabs** [comment]
Another possible benefit of doing this is that it removes at least one reason not to chunk structs (i.e. nested recursive structs) -- namely that it would have made reading struct fields async in js, but go has blocking IO.

**Comment by rafael-atticlabs** [comment]
Blocked by
 * [Completing graphql]
 * Removing usages:
    * https://github.com/attic-labs/attic/issues/628
    * https://github.com/attic-labs/noms/issues/3174
    * https://github.com/attic-labs/attic/issues/895

 * 


I think this has been proven to the point that I've made the goal more affirmative. This is blocked by:

* https://github.com/attic-labs/noms/issues/3173
* https://github.com/attic-labs/noms/issues/3175
* https://github.com/attic-labs/noms/issues/3176
* https://github.com/attic-labs/noms/issues/3174

**Comment by sunglim** [comment]
If Noms support graphql,   you're not going to support bindings to another language([C bindings](https://github.com/attic-labs/noms/issues/2718), C#, android, and ios) ?

**Comment by rafael-atticlabs** [comment]
Yes. For the near-future, at least, the approach will be for application code (js, swift, c#, c, java) to request and update data via graphql.

**Comment by gedw99** [comment]
This is more a thought experiment idea... Just saying..

i was thinking the same thing. If NOMS used GRPC for its API, then it woudl have been trivial to cross build clients in other languages, without GraphQL.
Also there its not that much work to parse the GraphQL schema and generate GRPC for it.
DGraph has some things it it similar to it.

**Comment by gavindoughtie** [comment]
So the dream of having a Gears-like browser data sync via NOMs dies? /me weeps

**Comment by rafael-atticlabs** [comment]
At least directly via JS. 

One possible route is to compile the go implementation via llvm to web assembly which would persist using indexeddb and run in a service worker. Client UI would read/write via GraphQL. The download size of the compiled go code is the obvious downside, but upside is probably speed since the main perf problem with JS (lack of control over memory allocations) would be removed. Also, at this point, the client always reads/writes via graphql but is either talking to a local store or a remote store.

There's no immediate plan to do this, but its possible.

**Comment by gavindoughtie** [comment]
Normally I'd be skeptical but if you guys can't make a JS implementation work then I'm just a sad panda. If, however, it's something that varies with data size perhaps it would still be useful to have small nodes sync'ing. (a single user's subgraph). Or maybe https://github.com/gopherjs/gopherjs?

**Comment by rafael-atticlabs** [comment]
Goodbye, my complicated friend:

https://github.com/attic-labs/noms/commit/3c764c1eb5178652d116cb05f8f325ba845c39e3

**Comment by arv** [comment]
It was good to know you -- Stockholm syndrome?
