### ISSUE TITLE
`Download the latest build` on setup.md is version 7.2

### ISSUE THREAD

**Issue by sunglim** [attic-labs/noms#3144]
`Download the latest build` on [README.md](https://github.com/attic-labs/noms/blob/master/README.md) version 7.2
But demo db(http://demo.noms.io/cli-tour) is version 7.0

Because of that , there's an compatibility error to use noms-cli with demo db.

**Comment by arv** [comment]
@mikegray can you update the readme to point at the 7.0 version instead?

**Comment by mikegray** [comment]
@arv did you try the download? For me both Download links on README.md are the same and both go to a version that is `format version: 7`. Can you please try it?

**Comment by arv** [comment]
@sunglim You need to get a binary that uses version 7.0 to talk to http://demo.noms.io/cli-tour

We do not have another demo server running version 7.2
