### ISSUE TITLE
Deploy graphql UI to `graphql.noms.io`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3172]
This will be increasingly important as we move to GraphQL

**Comment by zcstarr** [comment]
I've done the leg work and there's a PR out that will make things a bit  more uniform with jenkins, once it lands. 
https://github.com/attic-labs/noms/pull/3185

**Comment by zcstarr** [comment]
We're missing a css file with the deploy digging into it. graphiql.css

**Comment by zcstarr** [comment]
Think we're missing the css file in the build 
https://github.com/attic-labs/noms/blob/master/samples/js/graphiql/index.html#L11

**Comment by arv** [comment]
Can we copy it out of the node_modules directory in the staging script?

**Comment by arv** [comment]
This is done right?

**Comment by zcstarr** [comment]
yes
