### ISSUE TITLE
Implement type simplification v2

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3184]
Expand on the [initial design](https://github.com/attic-labs/noms/issues/2995) and "union" structs of the same name if one is reachable from another. replace "descendant" with `Cycle`. This explains how cycles are auto detected.

IOW: 

```
Struct Foo {
  a: String
  b: Struct Foo {
    a: String
  }
}
```

=>

```
Struct Foo {
  a: String
  b?: Cycle<1>
}
```

**Comment by rafael-atticlabs** [comment]
Needs clear design

**Comment by rafael-atticlabs** [comment]
Blocked on https://github.com/attic-labs/noms/issues/2327

**Comment by aboodman** [comment]
Clever.

**Comment by aboodman** [comment]
What are the motivations for this change OOC?

**Comment by rafael-atticlabs** [comment]
There's a few practical reasons:

-We get to tear out a bunch of complex and questionably correct code
-It removes a rather sharp edge in type accretion -- which is that types can (and tend to) get very large. Type simplification within unions helped dramatically, but there's still no guard against arbitrarily deep types.
-Developer ergonomics. The only time you'd need *create* a cyclical `Type` is if you wanted to declare it as an input or output of a job. Creating graphs which are logically cyclical would reduce down to cyclical types without you needing to think about it.

The bigger reason is: optional types. I think we need optional types for a bunch of reasons, and as soon as I think down the path of optional types, I arrive at the conclusion that `Types` in noms are really just a (lossy) summary of a graphs of noms values. The `kind` of a value is it's real *type*. What we think of as `Type` is really a meta description.

Until now we've allowed `Type` summaries to be encoded *within* types (e.g. with allowing `Value` and `Cycle` within struct types and via type simplification in collections).

It's just far simpler and far easier to reason about validity and correctness if `Type` is essentially always *computed from* values - rather than *asserted about* values.

**Comment by arv** [comment]
You mean optional fields, not optional types.

**Comment by rafael-atticlabs** [comment]
Yes. Sorry.

**Comment by rafael-atticlabs** [comment]
There is follow on work here:

-Fix tests/code uses which were assuming that all types are interned.
-https://github.com/attic-labs/noms/issues/3321
-https://github.com/attic-labs/noms/issues/3323
-https://github.com/attic-labs/noms/issues/3324
-https://github.com/attic-labs/noms/issues/3325
-https://github.com/attic-labs/noms/issues/3326
-https://github.com/attic-labs/noms/issues/3328

**Comment by arv** [comment]
![image](https://cloud.githubusercontent.com/assets/45845/24569020/2895e094-1619-11e7-9c76-1c7b13548428.png)
![image](https://cloud.githubusercontent.com/assets/45845/24569039/31388a4e-1619-11e7-9113-82b61611152b.png)

**Comment by rafael-atticlabs** [comment]
hey, @aboodman, we share a worry that the TypeSimpV2 world we're headed towards might be over kill.

practical problems:
1) bots in attic might not be able to specify input/output types as precisely as they'd like. 
2) more generally, it seems weird to disallow unsimplified types altogether (i.e. to be stored as values)
3) simplifying anonymous structs across levels (lifting fields is potentially confusing).

i believe the following is implementable:

0) Types are always canonical. I.e. the same logical type always has the same hash.

1) Types are *only ever* simplified automatically by noms when they are stored within a `Ref`. Basically types get simplified as type information crosses chunk boundaries. This implies that types get simplified within collections as they grow. IOW, a `List` which happens to a single chunk, won't have its type written anywhere in the chunk, and thus its type won't be simplified

2) `types.TypeOf(Value)` *never* simplifies. It always hands you back the most precise type based on the value you handed in. The same caveat as in (1) applies: If the value contains `Ref`s, the type of the thing they point to will have been simplified already. A corollary to this is that we add `types.SimplifyType(*Type)`.

3) Type simplification behaves as follows:
-Structs of the same name, *including anonymous structs*, within a union are simplified together
-*All named* structs within a simplified type are simplified together (thus inferring cycles). Cycles *cannot* exist to anonymous structs. IOW, fields are not "lifted" from anonymous structs and simplified from anonymous structs at another "level".

I believe this is implementable with relatively simple deterministic union ordering, as follows: A union is either *inside* or *outside* a simplified type.

Ordering *inside* a simplified type is: by struct name (because there can only be one of a given struct).

Ordering *outside* a simplified type is: by struct name, then by type hash. We know we can compute the type hash without fear of cycles because cycles can only occur within simplified types.

Thoughts?

**Comment by aboodman** [comment]
So `TypeOf(List<T1, T2>)` will have different value than `TypeOf(List<T1,T2,T1>)` if the latter chunks and the former doesn't?

**Comment by rafael-atticlabs** [comment]
Yes =-(

**Comment by rafael-atticlabs** [comment]
Well, another variant just `0` and `3`. 

-Types are always simplified
-Named and anonymous structs are simplified within unions
-Cycles are implicitly created between named structs only

**Comment by aboodman** [comment]
That seems better to me.

However we should also consider just scrapping cycles. People who need then
can workaround with Ref<Value>.

**Comment by rafael-atticlabs** [comment]
There's only the `IsSubtype(Type, Value)` bug remaining here, and that's just a perf issue. We can fix as needed. Closing this one.
