### ISSUE TITLE
Implement `unionTypes(a, b *types.Type) *types.Type`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3204]
This is a variant of the algorithm we have now for simplifying types. And when we add optional struct fields, it will *become* the algorithm for simplifying types.

The difference between union and simplify is that when simplify encounters two structs and a field is present in only one, it drops it. Union must keep it.

**Comment by ehalpern** [comment]
@aboodman: Given @rafael-atticlabs's suggestion that this ultimately replace makeSimplifiedUnion, do you still have reservations about implementing this in noms rather than attic?

**Comment by aboodman** [comment]
I think it might be easier to iterate at first with this in attic closer to
the calling code. But not a huge deal.
