### ISSUE TITLE
Implement `ViewOf(v types.Value, t *types.Value) types.Value`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3205]
`ViewOf` takes a value and a type and produces a new value.

Defined recursively:
* if t.Type() is not a subtype of t, return error
* if `v.Type().Equals(t) || t.Equals(types.ValueType)` return v
* switch t.Kind:
  * case: Struct:
    * return a new Struct with fields:
      * visit each field in `v`. if `t` has a corresponding field name and the the field value in `v` is a sub-type of the field value in `t`, include the field and set its value to be `ViewOf(sub-value, sub-type)`
  * case: Set, List, Map:
    * return a new Set, List or Map:
      * visit each value in the collection (k/v pair in the case of map). if the value's type is a sub type of  some element type of `t` include it and produce its value by `ViewOf(value, t.ElementType)`.

**Comment by aboodman** [comment]
Other potential names for this function: `ExtractSupertype`? `Filter`? `ExtractView`?

The verb `Extract` seems very apropos to me.

**Comment by aboodman** [comment]
I think `ExtractView` is nice. This thing is very similar to a `View` in other databases.

**Comment by aboodman** [comment]
I think it's also worth thinking what the full signature looks like assuming this is going to need to be implemented incrementally:

```
ComputeView(currInput, prevInput, prevView types.Value, viewType *types.Type, vrw types.ValueReadWriter) (view types.Value)
```

**Comment by rafael-atticlabs** [comment]
This is done in attic, right @aboodman

**Comment by aboodman** [comment]
yup
