### ISSUE TITLE
Implement ranged queries for collections via GQL

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3227]
For lists/sets/maps:

`elements(at:)` => returns single element
`elements(at:, count:)` => returns [at, at + count)

For sets/maps

`elements(key:)` => returns single element
`elements(key:, count:)` => returns count elements starting at key
`elements(key:, through:)` => returns elements [key, through]

**Comment by arv** [comment]
I'm also adding `keys`, which only works on maps but allows you to pass in multiple keys.
