### ISSUE TITLE
marshal omitempty creates invalid Go values

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#3239]
Consider this code:
```go
type Foo struct {
  MyMap types.Map `noms:",omitempty"`
}

// Note: missing the MyMap field.
fooValue := types.NewStruct("Foo", types.StructData{})

var foo Foo
marshal.Unmarshal(fooValue, &f)

// This crashes.
foo.MyMap.Type()
```

The `foo.Type()` line crashes because `MyMap` was initialised as an empty types.Map Go value, which has a null type.

marshal.Unmarshal needs to set MyMap to `types.NewMap()`, likewise presumably for Set/List.

@arv

**Comment by aboodman** [comment]
Hm, not so sure. What would you then expect to happen if you do:

```
marshal.Marshal(Foo{
  MyMap: types.NewMap(),
})
```

Do we leave off the field in Noms or encode the empty map. Both are possible.

I think what it does now is more self-consistent.

**Comment by kalman** [comment]
Yeah arv convinced me this issue is not the right thing to do. The workaround is to actually initialize `Foo` like you've said.

However the digging I needed to do to figure out why my program was crashing was a pain. I am going to do a run over noms to try to help future people.
