### ISSUE TITLE
Fix s3 'connection reset by peer' failures

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#3255]
3 pronged plan of attack:

1) update aws sdk (done)
2) add a VPC endpoint for a more stable connection to S3
3) log request ID (#3206) for use in support followup if needed

**Comment by rafael-atticlabs** [comment]
@cmasone-attic is this bug actionable at all? should be keep it open?

**Comment by cmasone-attic** [comment]
I think at this point we've worked around it and were pretty much out of options anyway :-/
