### ISSUE TITLE
UnhandledPromiseRejectionWarning running JS tutorial

### ISSUE THREAD

**Issue by gavindoughtie** [attic-labs/noms#3273]
Running noms server from noms-HEAD-darwin-amd64 directory (downloaded as of March 16, 2017). No warnings starting noms serve /tmp/noms-js-tour

> const db = noms.DatabaseSpec.parse('http://localhost:8000').database();
undefined
> (node:47972) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): HttpError: 400
(node:47972) DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by arv** [comment]
The following works for me:

```
$ noms serve /tmp/test &
Listening on port 8000...
$ node
> noms = require('@attic/noms')
...
> db = noms.DatabaseSpec.parse('http://localhost:8000').database()
Database {
...
}
```

@kalman

**Comment by arv** [comment]
FWIW, I'm using `@attic/noms`, `69.8.0`.

**Comment by arv** [comment]
Also see https://github.com/attic-labs/noms/issues/3120
