### ISSUE TITLE
"original" in struct prevents type marshaling

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#3284]
Consider:
```go
	type S struct {
		Foo int          `noms:",omitempty"`
		Bar types.Struct `noms:",original"`
	}
```
This is intentionally an error: https://github.com/attic-labs/noms/blob/master/go/marshal/encode_type_test.go#L355 because it doesn't make sense for "original" to be part of the type.

but it's actually pretty annoying as an error, I'd rather it just skip and let me marshal the type.

**Comment by aboodman** [comment]
Seems reasonable.

**Comment by arv** [comment]
Treating `original` as skip (`-`) when doing marshal type makes sense to me.
