### ISSUE TITLE
Does noms have a story for storing files?

### ISSUE THREAD

**Issue by samherrmann** [attic-labs/noms#3291]
Git has [git-lfs](https://git-lfs.github.com/), SQL Server has [FILESTREAM](https://technet.microsoft.com/en-us/library/bb933993(v=sql.105).aspx). Does noms have (or will have) a story for storing files?

**Comment by joeblew99** [comment]
i dont get it. It stores files on disk in its own format as it is right now.

**Comment by rafael-atticlabs** [comment]
Yes. Store files as `Blob`. See https://github.com/attic-labs/noms/tree/master/samples/go/blob-put
