### ISSUE TITLE
Contributing: Non-members are unable to assign PR

### ISSUE THREAD

**Issue by samherrmann** [attic-labs/noms#3297]
Step 5 of the [submitting PRs instructions](https://github.com/attic-labs/noms/blob/master/CONTRIBUTING.md#submitting-prs) requests developers to assign the PR to someone when it's ready for review. People like myself that are not members of the project do not have the necessary privileges to do that. What should non-members do instead to indicate that the PR is ready for review? Tag a member in a comment?

**Comment by aboodman** [comment]
Hm. Good point... Some of us typically keep tabs on all the PR mail, but is there something that is common in other Github projects? My reference point is still Chromium which uses different tools.

@arv, @kalman, @rafael-atticlabs ?

**Comment by aboodman** [comment]
Another related thing is that someone new to the project wouldn't necessarily know who to assign/tag.

**Comment by kalman** [comment]
Mostly I just see people monitoring PRs and reviewing them. Other projects have bots which do it but that seems too fancy.

**Comment by arv** [comment]
At this point we can just manually triage issues as they come in.

**Comment by aboodman** [comment]
I've updated the instructions. This all got easier since Github introduced their review feature.

Thanks for the feedback @samherrmann.
