### ISSUE TITLE
Type simplification needs to be done everywhere

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#3319]
We currently simplify types when we create union types. We should also do this when we create struct types.

We might also want to do this when we create map types (since the same struct can appear in the key and value type).

@rafael-atticlabs

**Comment by arv** [comment]
I think that by doing it in MakeStructType we can remove the custom type creation in datas.NewCommit.

**Comment by rafael-atticlabs** [comment]
Closing in favor of https://github.com/attic-labs/noms/issues/3184
