### ISSUE TITLE
Suggestion: Replace Roadmap in README with GitHub Milestones

### ISSUE THREAD

**Issue by samherrmann** [attic-labs/noms#3322]
I saw that issue #2327 is now closed, which is an item on the [roadmap](https://github.com/attic-labs/noms#roadmap). While the issue is closed, it was not checked off on the roadmap. The static nature of the roadmap makes this an easy oversight. I think GitHub's Milestones exists for the exact purpose for which you've created the roadmap and it will never report false status ;)

My apologies for the pedantic and low priority issues that I've been raising this week!

**Comment by aboodman** [comment]
Hm, right you are. But I like embedding the high high level overview right
in the homepage the way it is. Tradeoffs, tradeoffs.

**Comment by aboodman** [comment]
Don't apologize, we appreciate all the little sprucing.
