### ISSUE TITLE
Compute types lazily

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#3327]
![image](https://cloud.githubusercontent.com/assets/45845/24568596/5fce9c38-1617-11e7-91c2-9620e98a96ab.png)

![image](https://cloud.githubusercontent.com/assets/45845/24568613/70e0b51a-1617-11e7-8a16-8c50b38c9539.png)

**Comment by rafael-atticlabs** [comment]
closing in favor or https://github.com/attic-labs/noms/issues/3184
