### ISSUE TITLE
Implement MapIterator.Prev() (or equivalent)

### ISSUE THREAD

**Issue by ehalpern** [attic-labs/noms#3341]

**Comment by rafael-atticlabs** [comment]
OOC, what is this needed for?

**Comment by ehalpern** [comment]
See discussion of findInMap in https://github.com/attic-labs/attic/pull/1239
.

The use case is:
- A map is used to index values by time (or some other numeric value)
- Given a time, we'd like to find all values in the map that cluster near
that time
- To do this, we scan backward checking that the previous entry is within a
delta of the current entry until
  we find one that isn't. Then we scan forward doing the same check.
- This is currently implemented using Map.At(idx) and binary search outside
of noms.
- The implementation could be almost entirely replaced with
Map.IteratorFrom(), and MapIterator.Next()/Prev().
