### ISSUE TITLE
Consider removing PutMany

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#3344]
We added this when we created DynamoStore, and that's really the only place it helps us. Most (all?) other implementations just call Put() on all the elements of the provided slice.

As of https://github.com/attic-labs/noms/pull/3340 it will only be used in tests, so if we remove it from the ChunkStore API, we should consider making a helper function or something that can be used for those cases

**Comment by rafael-atticlabs** [comment]
Fixed
