### ISSUE TITLE
`marshall` should use `types.MakeStructTemplate`

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#3347]
We should look at usages of MakeStruct to see if we need to provide a function that does not need to use a map and sort the fields.

For struct types we have two different versions and we should fix the naming inconsistencies.

**Comment by arv** [comment]
For example samples/go/csv/... keeps creating the temporary map.

**Comment by aboodman** [comment]
Cuz what we needed was another way to create structs. =P

**Comment by arv** [comment]
We can remove the one that takes a `map[string]types.Value` if you want?

**Comment by arv** [comment]
There are more cases. For example, marshal can take advantage of this.

**Comment by rafael-atticlabs** [comment]
Yeah. Sorry I noticed that. I didn't see any other uses in noms. Changing bug title.

**Comment by arv** [comment]
Fixed in fff2d754817d98a01f6ccc080a3e14873847e2a8
