### ISSUE TITLE
Add datas.IsCommit

### ISSUE THREAD

**Issue by arv** [attic-labs/noms#3348]
We currently have `datas.IsCommitType`. It would be good to have one that operates on the value directly.

It would check:
 - That we have a struct named "Commit"
 - That we have meta, parents and value fields (and no other) and that they are non optional.
 - meta is a struct
 - parents is `Set<Ref<Cycle<Commit>>>`.

Maybe this would fall out from https://github.com/attic-labs/noms/issues/3326 ?

**Comment by rafael-atticlabs** [comment]
yeah, that's kind of what i meant about auditing the uses of TypeOf for cases that could just use IsSubtype(Type, Value)
