### ISSUE TITLE
Comparing Refs directly should be safe.

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3357]

**Comment by rafael-atticlabs** [comment]
https://github.com/attic-labs/noms/pull/3356 doesn't seem like it should have been neccesary. As an example, TestProgress in attic/util/status/status_test.go failed without it.

**Comment by arv** [comment]
One gut feeling is that if the Ref type is deep inside some other type then the type will not be the same as if it is created by itself:

```
Ref<struct A { a: Bool }
```

vs:

```
Map<
  struct A {},
  Ref<struct A { a: Bool }>
>

// which gets simplified to

Map<
  struct A { a?: Bool },
  Ref<Cycle<A>>
>
```

**Comment by rafael-atticlabs** [comment]
This was a result of the bug in cycle encoding. N/A.
