### ISSUE TITLE
Consider whether RootTracker makes sense as a separate interface

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#3402]
All ChunkStores are RootTrackers, but not vice-versa. This is a little weird, because `UpdateRoot()` (soon to be renamed `Commit()`) implies making a bunch of Chunks durable -- though a RootTracker has no way to put in chunks.

On one hand, it's nice to narrow the interface sometimes when handing out a ChunkStore if you don't want the caller to be able to get or put chunks. On the other hand, it's weird because you can't fully describe the semantics of RootTracker without referencing stuff you can only do through the full ChunkStore interface.

**Comment by rafael-atticlabs** [comment]
Agree. Without looking too hard at it, I think it might make sense to have ChunkRead, ChunkWriter and ChunkStore which embeds both and adds the methods from RootTracker.

**Comment by cmasone-attic** [comment]
Heh. In my patch, I actually wound up merging the existing `ChunkSource` and `ChunkSink` interfaces (analogous to your ChunkReader and ChunkWriter) because you also can't fully specify the semantics of `Put` and `PutMany` without referencing Has, Get et al which are part of ChunkSource

**Comment by rafael-atticlabs** [comment]
Yup. Makes sense now that I look at the patch. Those two things aren't really seperable etiher.
