### ISSUE TITLE
Add `ChunkStore/ValueStore/Database.Fork()`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3437]
The goal here is to allow someone to observe one state of a database, and then send N writers doing independent work (attempting to commit to different datasets) off using their own `Database` .

Thinking about this also clarified a bit in my head the concerns of Database & ValueStore.

Separate bug here: 

https://github.com/attic-labs/noms/issues/3436

**Comment by rafael-atticlabs** [comment]
Given the concurrency issues we've been struggling with in attic recently, I'd like to bump this idea again.

If we did this, the top-level cycle of attic simple retain a *single* database for each attic which Rebase()'d at the start of each loop. Ops can use it to check preconditions and *only when* they have work to do, `Fork()`.

@aboodman, @willhite ?

**Comment by rafael-atticlabs** [comment]
@cmasone-attic, I can imagine pretty easily the implementation of nbs.Store.Fork(). What do you think about `ValueStore.Fork()`?

**Comment by rafael-atticlabs** [comment]
A simple implementation could just flush to the chunkstore prior to forking it.

**Comment by cmasone-attic** [comment]
Can you be precise about the desired semantics?

**Comment by cmasone-attic** [comment]
and about what precisely "flush to the chunkstore" would do, since there's no longer a Flush() method on ValueStore. Would it make these chunks persistent?

**Comment by rafael-atticlabs** [comment]
I think if we called it `Fork` (as @aboodman points out), it probably has to be pretty darn close to forking a process.

**Comment by rafael-atticlabs** [comment]
I think another option here would be to split the storage interface into readers and transactions.

IOW, ChunkStore, et al wouldn't have `Put` or `Commit`, but rather `BeginTransaction`, which would return you a *writeable* `ChunkStoreTransaction` which embeds ChunkStore and reflects exactly the same snapshot as the `ChunkStore`, but it has `Put` and `Commit` on it.

An oplock failure would probably return false and "rebase()", but success would return true and return a new ChunkStore. IOW, it'd only be valid to commit once, thus kind of answering the question how exactly how multiple committers on a given store are supported.

**Comment by rafael-atticlabs** [comment]
I'm going to close this for now. The main reason to do this was to avoid the cost of opening/rebasing a ton of the same database at the same time, and now the manifest/tableIndex/smallTableCache are effectively removing that cost for most uses.
