### ISSUE TITLE
NBS: Avoid concurrent index parsing in mmapTableReader

### ISSUE THREAD

**Issue by cmasone-attic** [attic-labs/noms#3477]
Right now, if concurrent goroutines attempt to open a table whose index is not cached, they will all the work of reading and parsing the index. That's a bummer, and seems like we should avoid if we can.

FYI @rafael-atticlabs

**Comment by rafael-atticlabs** [comment]
Closing in favor of https://github.com/attic-labs/noms/issues/3536
