### ISSUE TITLE
Add `root` hash to `/getRefs` wire API

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3491]
Right now, for every request to `/getRefs`, we are forced to re-open or rebase a database. For NBS/AWS, this means a strongly consistent read against dynamo which costs money and adds ~10ms to the total latency.

There are still code paths that do lots of sequential reads of 1 chunk. For those paths, this is probably doubling the total latency for the AWS backend.

**Comment by cmasone-attic** [comment]
per discussion, I think this is actually going to be the root hash
