### ISSUE TITLE
Add process-wide manifest cache

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3492]
When an optimistic lock fails, nbs re-reads the manifest, but is frequently the case that this is because another in-process goroutine moved it.

For lock failures, we should attempt to move forward with the most recent in-process version before backing off to reading from disk/dynamo.

FWIW, I noticed this in some recent pprof profiles.

**Comment by cmasone-attic** [comment]
Fixed via #3503
