### ISSUE TITLE
NewStreamingSet is not checking inputs are sorted correctly

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#3560]
It tries to (https://github.com/attic-labs/noms/blob/master/go/types/set.go#L50) but lastVal is never assigned to, so the check doesn't work.

**Comment by rafael-atticlabs** [comment]
@willhite, please ensure that there are tests for map & set (looks to me like the bug only applies to set). 

Also, please bump noms version with fix.

**Comment by rafael-atticlabs** [comment]
@willhite, is there anything left to do here?
