### ISSUE TITLE
`IterAll` should use `LoadLeafSequences` rather than `readAheadLeafCursors`

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3568]

**Comment by kalman** [comment]
Is "most aggressive read-ahead" defined anywhere?

**Comment by rafael-atticlabs** [comment]
I think it is now LoadLeafSequences. Ping me if you want to discuss further.

**Comment by kalman** [comment]
As in adapt the blob loading code? Will ping you when I'm ready to start.

**Comment by rafael-atticlabs** [comment]
Yup.

**Comment by rafael-atticlabs** [comment]
I think the approach here would be to basically mimic `Blob.Copy`. The main rub here is knowing how many items to read ahead by. I'd be tempted to have a fixed initial estimate of items/leafSequence (this could be a const to begin with, but eventually based on the `Type`). As read-ahead takes place, you can update the estimate of values/leafSequence based on what was recently observed.

**Comment by kalman** [comment]
This is done for List. We still need to do it for Set and Leaf.

**Comment by kalman** [comment]
done in https://github.com/attic-labs/noms/pull/3761
