### ISSUE TITLE
Is there a way to clone or fork a noms dataset without any history.

### ISSUE THREAD

**Issue by arepx** [attic-labs/noms#3580]
I would like to share a noms dataset with a third party but I do not want to share the history or WIP branches.

Does noms support something similar to git clone --depth

```
--depth <depth>
Create a shallow clone with a history truncated to the specified number of commits. Implies --single-branch unless --no-single-branch is given to fetch the histories near the tips of all branches. 
...
```

**Comment by aboodman** [comment]
Noms doesn't support dangling pointers, but you can do this by creating a new dataset with same value, but no history:

```
noms commit ds.value $db::newds
```

Then share `$db::newds`. If you want you can delete the old dataset entirely:

```
noms ds -d $db::ds
```

**Comment by arepx** [comment]
Thats great, thanks.
