### ISSUE TITLE
Getting Started steps broken

### ISSUE THREAD

**Issue by sco** [attic-labs/noms#3587]
Per the Getting Started section of the README, I run `./noms ds http://demo.noms.io/cli-tour` but get the error "Unexpected response: Internal Server Error".

I'm using the [latest Darwin pre-built binary](https://s3-us-west-2.amazonaws.com/downloadstable.noms.io/jobs/NomsBuildGoBinaries-v7/4/noms-HEAD-darwin-amd64.tar.gz).

Stack:

```
goroutine 1 [running]:
panic(0x675dc0, 0xc4201da880)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/attic-labs/noms/go/d.Panic(0x6f233c, 0x17, 0xc420183510, 0x1, 0x1)
        /var/workspace/src/github.com/attic-labs/noms/go/d/try.go:37 +0x13e
github.com/attic-labs/noms/go/datas.(*httpBatchStore).Root(0xc420016c80, 0x0, 0x0, 0xc400000000)
        /var/workspace/src/github.com/attic-labs/noms/go/datas/http_batch_store.go:426 +0x2ff
github.com/attic-labs/noms/go/datas.newDatabaseCommon(0xc42015aba0, 0xc420016d00, 0xa3c340, 0xc420016c80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /var/workspace/src/github.com/attic-labs/noms/go/datas/database_common.go:31 +0x5c
github.com/attic-labs/noms/go/datas.NewRemoteDatabase(0xc42015ab40, 0x1c, 0x0, 0x0, 0x1)
        /var/workspace/src/github.com/attic-labs/noms/go/datas/remote_database_client.go:19 +0x355
github.com/attic-labs/noms/go/spec.Spec.createDatabase(0x7fff5fbffcb2, 0x1c, 0x7fff5fbffcb2, 0x4, 0x7fff5fbffcb7, 0x17, 0x0, 0x0, 0x0, 0x0, ...)
        /var/workspace/src/github.com/attic-labs/noms/go/spec/spec.go:264 +0x4eb
github.com/attic-labs/noms/go/spec.Spec.GetDatabase(0x7fff5fbffcb2, 0x1c, 0x7fff5fbffcb2, 0x4, 0x7fff5fbffcb7, 0x17, 0x0, 0x0, 0x0, 0x0, ...)
        /var/workspace/src/github.com/attic-labs/noms/go/spec/spec.go:148 +0x9f
github.com/attic-labs/noms/go/config.(*Resolver).GetDatabase(0xc42015ab00, 0x7fff5fbffcb2, 0x1c, 0x77c5d, 0xc420124000, 0xc420183ae0, 0x54585)
        /var/workspace/src/github.com/attic-labs/noms/go/config/resolver.go:95 +0x154
main.runDs(0xc420113a40, 0x1, 0x1, 0x0)
        /var/workspace/src/github.com/attic-labs/noms/cmd/noms/noms_ds.go:57 +0xc1
main.main()
        /var/workspace/src/github.com/attic-labs/noms/cmd/noms/noms.go:77 +0x438
```

**Comment by aboodman** [comment]
Hi scott! I will check it out.

**Comment by aboodman** [comment]
@ehalpern it looks like during the great dynamo cleanup, something got messed up. I'm seeing that the dynamo table the server is trying to access doesn't exist in the logs for the server. Not sure what the schema was supposed to be.

**Comment by aboodman** [comment]
@sco, sadly the server looks completely bork right now. I can't think of a workaround. Will try to get it back up soon.

**Comment by sco** [comment]
No rush, I'll keep an eye on it. Thanks!

**Comment by ehalpern** [comment]
Should be fixed. Please let me know @sco if you're still having problems.

There were two issues: 

1) The demo-server-2-manifests dynamo table had been deleted
2) The version of noms installed on the server was incorrect and causing date imported cron jobs to fail

To fix, I've created new, more clearly named tables
 - dynamo: noms-demo-manifests
 - s3: noms-demo-tables

And updated the noms binary.

I've also backed up the AMI so we have a working snapshot.

**Comment by aboodman** [comment]
Cool, it's wfm now. Thanks @ehalpern.

@sco, note that Noms on master has a bunch of awesome new stuff in it. So depending on what you're up to, it might make more sense to use it instead.
