### ISSUE TITLE
Can't address into Type using path syntax

### ISSUE THREAD

**Issue by kalman** [attic-labs/noms#3622]
It's fairly common to be writing Types into Noms for the botrunner reg dataset, but paths have no way to descend into those.

Case in point:
```
> ./noms show db::foo/reg.value.inputs[0]@type'
Type

> ./noms show db::foo/reg.value.inputs[0]'
struct Photo {
  blob: Ref<Blob>,
  id: struct ID {
    owner: String,
    value: String,
  },
  orientation: Number,
}

> ./noms show db::foo/reg.value.inputs[0].blob
Object not found
```

There are 2 relevant complex types (see https://godoc.org/github.com/attic-labs/noms/go/types): struct types, and compound types.
* It's logical to continue to use the `.blob` syntax for struct types, like I tried to do above.
* We can use the `[0]` syntax for compound types, i.e. `[0]` would be the ref/set/list value type, and the map key type, and `[1]` would be the map value type.

@arv @aboodman

**Comment by aboodman** [comment]
You could also use `.elem` and `.key`/`.value` but for some reason `[0]` and `[1]` seem more expected to me.

**Comment by arv** [comment]
`[n]` would also be better for union types.

**Comment by aboodman** [comment]
How would you address the name of a struct :( ?

@name I suppose. Annotations to the rescue again.

**Comment by kalman** [comment]
Does the name of the struct need to be addressed (for both struct values and struct types)?

If so I agree `@name` is the way to g.
