### ISSUE TITLE
Sequence chunker should avoid eagerly persisting root chunk

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3645]
Now that prolly trees are eagerly written on creation, the sequence chunker chunker should avoid persisting the root chunk (which is returned). This is important, because the root chunk may not be directly addressable in the resulting value (i.e. if it is embedded into another value).

**Comment by kalman** [comment]
Started looking at this. It isn't trivial when you consider all of the special cases listed at https://github.com/attic-labs/noms/blob/759cf4fe589dd8a0af4e08983637c8b10cff29cc/go/types/sequence_chunker.go#L204 (`sequenceChunker.Done`), namely that we don't really know what the root chunk is until `Done` is called.

Oh well, here goes...
