### ISSUE TITLE
IPFS deps are being linked into all noms clients

### ISSUE THREAD

**Issue by rafael-atticlabs** [attic-labs/noms#3709]
```
Rafaels-MacBook-Pro-2:csv-export rafael$ git reset --hard 1a7e006862eb1e16cfd9901f0c6b0204100b09a1
HEAD is now at 1a7e0068 Landing beginning of IPFS experiment on trunk (#3625)
Rafaels-MacBook-Pro-2:csv-export rafael$ go build
Rafaels-MacBook-Pro-2:csv-export rafael$ ls -la csv-export 
-rwxr-xr-x  1 rafael  staff  33759076 Sep 15 05:36 csv-export
Rafaels-MacBook-Pro-2:csv-export rafael$ git reset --hard 8b5cd66cceb8d1204dd55b428c36b108e779b93e
HEAD is now at 8b5cd66c NBS: Expose hashes request builder for use in tests (#3630)
Rafaels-MacBook-Pro-2:csv-export rafael$ go build
Rafaels-MacBook-Pro-2:csv-export rafael$ ls -la csv-export 
-rwxr-xr-x  1 rafael  staff  12743332 Sep 15 05:37 csv-export
```

e.g. nearly tripped the size of the `csv-export` binary

**Comment by kalman** [comment]
I presume this is for spec parsing, and I'm not sure you can do much about that:

https://github.com/attic-labs/noms/blob/1e6a54d89f91061690ce6d5c153cdf69db72176f/go/spec/spec.go#L185

@willhite 
@arv mentioned something in slack about this a while back too

**Comment by willhite** [comment]
We could add some api that allowed clients to add protocols dynamically and we could use that for our IPFS chat application. The nice thing is that noms and all of other utils/samples would be unencumbered by IPFS libraries, the downside is that they wouldn't  work with IPFS-based databases. :-(

**Comment by aboodman** [comment]
I think it is fine to make it pluggable. Just somebody needs to design the
contract with spec package.
