### ISSUE TITLE
Create a Dockerfile

### ISSUE THREAD

**Issue by stevepeak** [attic-labs/noms#3789]
Add a Dockerfile and officially support a Docker build to help adaption rate and customer onboarding.

@dustywilson I found your [Docker build ](https://hub.docker.com/r/scjalliance/noms/~/dockerfile/) and would love to know if you had any issues or feedback that could help Noms create an official Dockerized version of the product. Thanks!

**Comment by stevepeak** [comment]
I've created the organization on Docker Hub https://hub.docker.com/u/noms/ -- will transfer over ownership to the main contributors once I get their emails to invite. 👍

**Comment by aboodman** [comment]
Maybe add the missing deps you found @stevepeak?

**Comment by stevepeak** [comment]
Certainly! I'll be submitting a PR soon with a working container and instructions on how to maintain (which I'm happy to do).

**Comment by dustywilson** [comment]
@stevepeak We haven't been using it lately, but when we were using it we had zero problems whatsoever.  You're welcome to use the Dockerfile I created verbatim or modified however you want.  Mine was super simple and worked fine, but I don't know if there have been any important changes in recent times that would cause you to want to make a change as to how it is done.  I know that new features have come out for Docker to support multi-stage builds, so you could, in theory, build it in such a way that you use golang base image to do the build, but then distribute a container that contains literally one single binary (assuming there's no shelling out for anything, need non-embedded CA certs, etc).  If I were to re-implement now, that's what I would do.

https://docs.docker.com/engine/userguide/eng-image/multistage-build/ has info on how to go about doing that, and I highly recommend understanding that before proceeding with a new Dockerfile.

**Comment by kav** [comment]
Looks like the Dockerfile in the repo is pretty good. Any chance someone can publish it to the noms organization in dockerhub so the rest of us can just pull it from there?

**Comment by emmaly** [comment]
FYI we're going to delete our repo at scjalliance/noms.  Your Dockerfile in this repo is looking very good, so I see no point in keeping the one at scjalliance around.  (FYI I was formerly @dustywilson, but changed username.)  Thanks for taking this task forward!

**Comment by aboodman** [comment]
> Might also want to add:

Done.

**Comment by aboodman** [comment]
> Any chance someone can publish it to the noms organization in dockerhub so the rest of us can just pull it from there?

Done: https://hub.docker.com/r/noms/noms/.

**Comment by aboodman** [comment]
I also set it up to autobuild, so it should stay up to date.
