### ISSUE TITLE
contributor agreement links no longer exist

### ISSUE THREAD

**Issue by senorsmile** [attic-labs/noms#3793]
There are links to individual and corporate contributor agreements at: 
https://github.com/attic-labs/noms/blob/master/CONTRIBUTING.md

However, both of them produce the following error: 
```
<Code>NoSuchBucket</Code>
<Message>The specified bucket does not exist</Message>
```

**Comment by aboodman** [comment]
Yep, agreed. We are investigating how to change this process as the old one involved assigning copyright to "Attic Labs, Inc", which no longer exists.

**Comment by aboodman** [comment]
Fixed, thanks again for the report.
