### ISSUE TITLE
What are the future plans for this project?

### ISSUE THREAD

**Issue by ccorcos** [attic-labs/noms#3812]
I'm considering using Noms as the basis for a new project but I don't want to start down a dead end. Is this project still being actively developed?

**Comment by rafaelweinstein** [comment]
HI @ccorcos, there isn't any active development of this project right now. @aboodman may be making periodic commits, but other than that the team which created this is mostly occupied on other work.

**Comment by ccorcos** [comment]
Ah. That's too bad. What are you working on now?
