### ISSUE TITLE
What is the remaining implementation for the production ready?

### ISSUE THREAD

**Issue by sairoutine** [attic-labs/noms#3833]
Hello @attic-labs team!
My team are currently using noms to develop the application for the production.

It seems that attic labs team are tied up with their other works, so we have the will to develop remaining implemention if needed.

I have two questions.

1. What is the remaining implementation for the production ready?
2. Could you give me a collaborator permission if our contribution will be welcomed?

noms is an awesome product we are passionate to use, Thanks.

**Comment by aboodman** [comment]
Hi @sairoutine - it's nice to hear you are having success with Noms so far.

There's nothing in particular blocking "productionization" feature-wise, IMO. For many applications, I could imagine that the following missing features could be important to you:

1/ [garbage collection](#3374)
2/ [sync long commit chains](#2233)

... but for more basic applications, even these features could be non-critical. It depends on your needs.

The main thing that is "missing" is that *Noms has never been used in production*: you will be the first. And it is not actively supported by anyone, so you will be on your own. There will certainly be bugs, which I will try to respond to, but there is no commitment.

As for your other questions: we have given collaborator permissions in the past for people with a history of good contributions, but we don't have a documented policy on it. 

I hope this helps.

**Comment by sairoutine** [comment]
Thank you for your information. It helps me a lot!
I'll keep working on using noms while fix it if necessary.
