### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by kschwidder** [attic-labs/noms#3847]
Noms is a promising approach to solve several topics. Looking at the contributions it seems that noms is stalling. Is that right or is noms increasing on delivering a roadmap.

**Comment by aboodman** [comment]
Noms is stalled for now. I expect development to pick up somewhat in the new year.

**Comment by aboodman** [comment]
(and thanks, btw -- would love to hear what problems you are looking at and help to the extent possible).

**Comment by aboodman** [comment]
I've updated https://github.com/attic-labs/noms/blob/master/README.md#status to try and make this more clear.

**Comment by kschwidder** [comment]
Thx for your comments ! I am working in the EAM world and would like to build a ground braking approach similar to git. The base idea is about documents and relationships. Documents are immutable and versioned to see the history of changes. Relationships are building a graph representation and it should be possible to create branches of a sub graph with all associated documents. Branches could be changed etc. and merged back into the main database.
Therefore the norm approach seems to fit for it :-)
While using grahql as the query engine a headless environment with decentralized databases would fit perfectly. 
Is that worth to do so with norm ?
Kind regards
