### ISSUE TITLE
no release has been issued since April

### ISSUE THREAD

**Issue by coriolinus** [attic-labs/noms#3855]
While of course it doesn't make sense to release unfinished code, it would be nice to get at some of the new features (in particular `go mod` support) since then without living entirely on the edge and depending on `master`. A point release soon, here and on docker hub, would be very useful.

**Comment by aboodman** [comment]
Huh, I thought the binaries on the homepage were autoupdating, but they apparently aren't. Will try to push one right now. As for the docker build, it's hard to keep it going because I'm not a big docker user.

**Comment by coriolinus** [comment]
It is possible to configure CI in general to rebuild the image and push to docker hub on every release--the hard part is just finding an appropriately secure place to store the docker hub credentials. I haven't done a lot with Travis configuration, but is this an area where you'd be receptive to PRs?

**Comment by aboodman** [comment]
Yeah sure, but I can't really engage in it for the next week or so. Sorry!

**Comment by aboodman** [comment]
Also: I don't know what's going on with the build. I just kicked off a new one, and it failed twice in a row in a spot related to my latest changes. However that same build previously succeeded.

Grump. Sorry I don't have time to look at it right now.

**Comment by michaelpalumbo** [comment]
since dev on this is on pause, are there similar db projects that are currently active (and actively supportive?)

**Comment by aboodman** [comment]
Few things:

1. Sorry for the delay here. I pushed a new release: https://github.com/attic-labs/noms/releases/tag/latest. I don't need Docker support right now, so I'm afraid I don't have the bandwidth to figure this out. @coriolinus if you are interested, I'm happy to have help. Travis does have a way to store secrets.

2. Now that Go modules exist and there's a strong convention for how versioning works in Go-land, I'd like to move to it. Right now Noms conflates library version and format version (not to mention CLI and HTTP interface version) in one number. However, the format version is very important -- two Noms nodes can only talk to each other if they speak the exact same format. Changing the library in an incompatible way shouldn't make those two nodes unable to sync to each other, but currently it does.

3. As for alternate projects. I am aware of https://github.com/liquidata-inc/dolt. It was forked from Noms and is going in a different direction. You might check that out.

**Comment by aboodman** [comment]
I put a concrete proposal for versioning here: https://github.com/attic-labs/noms/issues/3867

Please comment if you have an opinion. Otherwise, I'll make this change soon.
