### ISSUE TITLE
nomdl.Parse(): Incorrect result

### ISSUE THREAD

**Issue by aboodman** [attic-labs/noms#3868]
`nomdl.Parse("[map {}]")` should return `types.NewList(vs, types.NewMap(vs)))`, but it actually returns an empty list.

**Comment by aboodman** [comment]
@arv fyi, if you're bored :).

**Comment by arv** [comment]
I'll try to get my golang env working again

**Comment by aboodman** [comment]
It should be super easy. I've converted Noms to use Go modules, so it should be easier to get building and so-on than before. You just need to upgrade to a recent Go.

**Comment by aboodman** [comment]
I just created https://github.com/attic-labs/noms/blob/master/HACKING.md. Untested, but should be 75% correct.

**Comment by arv** [comment]
Turns out that this fails because of:

https://github.com/attic-labs/noms/pull/3586#discussion_r127086685

The map is empty so it is not added to the list :'(

I wonder what breaks if we change this behavior?

**Comment by aboodman** [comment]
Bummer. Off the top of my head, the opposite default behavior makes more
sense. If you want to remove the empty item container you can just remove
it too. Want to try changing it and see if any tests break? If they don't
I'm fine risking it.

**Comment by aboodman** [comment]
Thank-you very much for looking at this, btw. Totally fine if you've had your yearly fill of Noms :). I can take it from here too.
