### ISSUE TITLE
Make assert.Equals() call Value::Equals()

### ISSUE THREAD

**Issue by rafaelweinstein** [attic-labs/noms#7]
It's easy to accidentally use assert.Equals() on two values. This will sometimes work, but it depends on whether the internal caches inside the two values are populated or not. Instead, we should be calling Value::Equals().

It should be possible to use some Go interface trickery to make assert.Equals() automatically delegate to Value::Equals() but it is complicated by the fact that the dbg package would then depend on types, which already depends on dbg.

**Comment by rafael-atticlabs** [comment]
Nope, testify needs to die in a fire

**Comment by aboodman** [comment]
heh
